toss/suspensive

docs/react-boundary/docs/intro/installation.md

Thank you for the good library.
There was a small bug, so I fixed it😁

docs(react-boundary): yarn install should be add keyword

---

.github/labeler.yml
.github/workflows/labeler-workflow.yml

Create a workflow that automatically creates a label for PR when changes or certain types of changes occur.
- In the monorepo, You can quickly see which of the many packages you've changed that PR.
- If the project is flowing and check the past PR, you can check the records of the past PR according to label.
The folder or label name is set by me, so you can modify the label name in a better direction!

chore: track changes and label them appropriately on PR

---

.github/CODEOWNERS

@ChanhyukPark-Tech  Let's go forward with me please 🚀

chore(.github): add ChanhyukPark-Tech as CODEOWNERS

---

packages/react/src/Delay.spec.tsx

test(react): wrote test code for verifying `Delay`.

---

packages/react/src/Delay.spec.tsx
packages/react/src/Delay.tsx
packages/react/src/SuspensiveProvider.spec.tsx
packages/react/src/index.ts
packages/react/src/withDelay.spec.tsx
packages/react/src/withDelay.tsx

related #62 
I refactor Delay.spec.tsx concisely too. If you mind, comment on code please.

test(react): add test case for SuspensiveProvider

---

packages/react/src/Suspense.spec.tsx
packages/react/src/SuspensiveProvider.spec.tsx
packages/react/src/hooks/index.ts

related #62
I added test case.

test(react): add test case for Suspense

---

configs/jest/jest.config.js
packages/react/src/Delay.spec.tsx
packages/react/src/Suspense.spec.tsx
packages/react/src/SuspensiveProvider.spec.tsx
packages/react/src/test-utils/index.tsx
packages/react/src/withDelay.spec.tsx
packages/react/src/withSuspense.spec.tsx
packages/react/tsconfig.build.json

related #62 
ps. add test case for withSuspense

refactor(react): remove repetitive code, name intuitively

---

configs/eslint-config-ts/noimport.js
packages/react/src/Delay.tsx

Introducing ESLint conventions to the Suspensive library by discovering some deprecated code in the Suspensive code base.
- Added rule `no-unused-vars` to ESLint configuration
- Adjusted existing code to follow this rule
- This PR does not impact users directly but improves the code quality and maintainability by preventing unused code from being committed to the project.

fix: add eslint rule to detect dead code

---

.gitignore
configs/rollup/index.js
configs/rollup/package.json
pnpm-lock.yaml

I add to visualize @suspensive/react, @suspensive/react-query's bundle size

chore(react): add rollup-plugin-visualizer

---

.github/workflows/ci.yml
packages/react-query/package.json
packages/react-query/tsconfig.json
packages/react/package.json

1. I removed unnecessary things to fix type:check
2. add type:check in ci.yml

fix(type:check): remove unnecessary tsc option

---

packages/react/src/ErrorBoundary.tsx
packages/react/src/__test__/ErrorBoundary.spec.tsx

related #121 
I make this Pull Request for this comment

fix(react): prevent nullish fallback TypeScriptly

---

.github/labeler.yml
.github/workflows/labeler.yml

I made labeler shortly, add more detail

fix(labeler): shortly, add more detail

---

configs/tsup/package.json
configs/tsup/src/index.ts
configs/vitest/package.json
configs/vitest/src/index.ts
package.json
packages/react-query/package.json
packages/react/package.json
pnpm-lock.yaml
turbo.json

I added helpful scripts
- clean
- build:watch
- test:watch

chore: helpful scripts

---

.github/labeler.yml

fix(labeler.yml): update

---

.changeset/wet-zebras-fail.md
packages/react-query/package.json
packages/react/package.json
websites/docs/package.json
websites/visualization/package.json

fix #143
1. description
2. funding
3. keywords
4. author
5. homepage
6. bugs

chore(package.json): more detail

---

packages/react/src/experimental/Await.en.mdx
packages/react/src/experimental/Await.ko.mdx
packages/react/src/experimental/_category_.json
websites/docs/i18n/ko/docusaurus-plugin-content-docs/current.json

docs(react): documentation for experimental Await

---

codecov.yml

I want to remove too much failing because of codecov/patch like below picture

ci(codecov): remove codecov/patch

---

.changeset/chilly-drinks-change.md
packages/react/src/ErrorBoundary.tsx

refactor(react): clarify variable name

---

packages/react/package.json
packages/react/src/utils/assert.spec.ts

I left comment to describe what I changed

test(react): modify assertion test code.

---

packages/react/src/utils/hashKey.spec.ts
packages/react/src/utils/hashKey.ts

related with #62
introduces a series of tests to ensure the correct behavior of the `isPlainObject` function.
AS-IS
TO-BE

test(react): add isPlainObject case

---

packages/react/src/AsyncBoundary.spec.tsx
packages/react/src/Delay.spec.tsx
packages/react/src/ErrorBoundary.spec.tsx
packages/react/src/ErrorBoundaryGroup.spec.tsx
packages/react/src/Suspense.spec.tsx

fix #168
I added spec to check displayName of all HOCs thanks to @tooooo1

test(react): add spec for HOC's displayName

---

.changeset/eleven-lobsters-divide.md
packages/react/src/experimental/Await.spec.tsx
packages/react/src/experimental/Await.tsx

- add getError, remove unnecessary generic
- update wrong test cases for awaitClient's error

feat(react): add getError, remove unnecessary generic

---

.changeset/dull-brooms-confess.md
packages/react-query/package.json

fix(react-query): correct peerDeps version

---

packages/react/src/Suspense.en.mdx
packages/react/src/Suspense.ko.mdx

docs(react): update doc of suspense

---

packages/react-query/src/QueryErrorResetBoundary.en.mdx
packages/react-query/src/QueryErrorResetBoundary.ko.mdx
packages/react/src/AsyncBoundary.en.mdx
packages/react/src/AsyncBoundary.ko.mdx
packages/react/src/Delay.en.mdx
packages/react/src/Delay.ko.mdx
packages/react/src/ErrorBoundary.en.mdx
packages/react/src/ErrorBoundary.ko.mdx
packages/react/src/ErrorBoundaryGroup.en.mdx
packages/react/src/ErrorBoundaryGroup.ko.mdx
packages/react/src/Suspense.en.mdx
packages/react/src/Suspense.ko.mdx
packages/react/src/SuspensiveProvider.en.mdx
packages/react/src/SuspensiveProvider.ko.mdx
packages/react/src/experimental/Await.en.mdx
packages/react/src/experimental/Await.ko.mdx

related with #172
describe component as bracket in official docs

docs: describe component as bracket

---

packages/react/src/ErrorBoundary.en.mdx
packages/react/src/ErrorBoundary.ko.mdx
packages/react/src/Suspense.en.mdx
packages/react/src/Suspense.ko.mdx

I updated doc for ErrorBoundary

docs(react): update doc for ErrorBoundary

---

packages/react/src/Suspense.en.mdx
packages/react/src/Suspense.ko.mdx

docs(react): update doc for Suspense

---

packages/react/src/AsyncBoundary.en.mdx
packages/react/src/AsyncBoundary.ko.mdx
packages/react/src/Suspense.en.mdx
packages/react/src/Suspense.ko.mdx

I updated doc for AsyncBoundary

docs(react): update doc for AsyncBoundary

---

.changeset/modern-hotels-perform.md
packages/react-query/src/QueryErrorResetBoundary.en.mdx
packages/react-query/src/QueryErrorResetBoundary.ko.mdx
packages/react-query/src/useSuspenseInfiniteQuery.en.mdx
packages/react-query/src/useSuspenseInfiniteQuery.ko.mdx
packages/react-query/src/useSuspenseQueries.en.mdx
packages/react-query/src/useSuspenseQueries.ko.mdx
packages/react-query/src/useSuspenseQuery.en.mdx
packages/react-query/src/useSuspenseQuery.ko.mdx
packages/react/src/ErrorBoundary.en.mdx
packages/react/src/ErrorBoundary.ko.mdx
packages/react/src/Suspense.en.mdx
packages/react/src/Suspense.ko.mdx
websites/docs/intro/visualization.en.md
websites/docs/intro/visualization.ko.md

I updated tips as admonitions
@okinawaa, when you compare change, I think the easiest way to compare the differences is to open two screens, one with dev server on one side and the other with production suspensive.org. I would appreciate it if you could make that comparison.

docs(react): update tips as admonitions

---

CONTRIBUTING.md

First of all, @okinawaa thank you for starting to write CONTRIBUTING.md. It was nice that most of the content was filled in. I thought about ways in which we could improve further.
1. I hope that by making the document more concise, readers will be able to contribute to our repository more quickly. Please let me know if there are any parts that were removed that are necessary. Let's add that part back.
2. I tried to write official words (GitHub, Pull Request, Workflows) with their full names in capital letters rather than using abbreviations.
3. Some links have been modified.

docs(CONTRIBUTING.md): add suggestion

---

CONTRIBUTING.md

fix #191 
Later, I'll do the translation work on another PR Let me know if there's anything missing!

docs: write contributing.md 

---

.changeset/olive-hounds-nail.md
README.md
packages/react-query/src/QueryErrorResetBoundary.en.mdx
packages/react-query/src/QueryErrorResetBoundary.ko.mdx
packages/react/src/AsyncBoundary.en.mdx
packages/react/src/AsyncBoundary.ko.mdx
packages/react/src/ErrorBoundary.en.mdx
packages/react/src/ErrorBoundary.ko.mdx
packages/react/src/ErrorBoundary.spec.tsx
packages/react/src/ErrorBoundary.tsx
packages/react/src/ErrorBoundaryGroup.en.mdx
packages/react/src/ErrorBoundaryGroup.ko.mdx
packages/react/src/ErrorBoundaryGroup.spec.tsx
packages/react/src/ErrorBoundaryGroup.tsx
packages/react/src/experimental/Await.spec.tsx
packages/react/src/utils/assert.ts
packages/react/src/utils/toTest.tsx
websites/visualization/src/app/react/experimental/await/page.tsx
websites/visualization/src/components/RejectedFallback.tsx

refactor(react): to easier code

---

packages/react/src/ErrorBoundary.en.mdx
packages/react/src/ErrorBoundary.ko.mdx

@minsoo-web, I fully understood your intention, I added suggestion to advise/useErrorBoundaryProps branch. merge this please if you ok
You can check preview of vercel made by this Pull Request.

docs(react): suggestion to advise/useErrorBoundaryProps

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

I added contributing section and contributors
Thank you @okinawaa's adding CONTRIBUTING.md

docs(README.md): update contributing and contributors

---

.github/CODEOWNERS
.github/workflows/release.yml

I added @minsoo-web as CODEOWNERS, releaser
@minsoo-web, Check your all information(email, GitHub username, etc.). If you ok, approve and merge this Pull Request

chore: add minsoo-web as CODEOWNERS, releaser

---

.changeset/curly-coins-hug.md
README.md
docs/src/pages/docs/react-query/installation.en.mdx
docs/src/pages/docs/react-query/installation.ko.mdx
docs/src/pages/docs/react-query/useSuspenseInfiniteQuery.en.mdx
docs/src/pages/docs/react/installation.en.mdx
docs/src/pages/docs/react/installation.ko.mdx
docs/src/pages/index.en.mdx
docs/src/pages/index.ko.mdx
packages/react-query/src/QueryAsyncBoundary.tsx
packages/react-query/src/QueryErrorBoundary.tsx
packages/react-query/src/useSuspenseInfiniteQuery.ts
packages/react-query/src/useSuspenseQuery.ts
packages/react/src/AsyncBoundary.tsx
packages/react/src/ErrorBoundary.tsx
packages/react/src/ErrorBoundaryGroup.tsx
packages/react/src/Suspense.tsx

I update jsdoc links and some chores
1. I read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)

docs: update jsdoc links

---

codecov.yml

chore: update codecov for @suspensive/react-await

---

.changeset/chilly-owls-buy.md
packages/react/src/hooks/useTimeout.spec.tsx

test(react): add useTimeout test case

---

docs/src/pages/docs/react-query/useSuspenseInfiniteQuery.en.mdx
docs/src/pages/docs/react-query/useSuspenseInfiniteQuery.ko.mdx
docs/src/pages/docs/react-query/useSuspenseQueries.en.mdx
docs/src/pages/docs/react-query/useSuspenseQueries.ko.mdx
docs/src/pages/docs/react-query/useSuspenseQuery.en.mdx
docs/src/pages/docs/react-query/useSuspenseQuery.ko.mdx
docs/src/pages/docs/react/Delay.ko.mdx

I provided a better guide by adding hyperlinks

docs(react): add hyperlink

---

packages/react/src/hooks/useIsomorphicLayoutEffect.spec.ts

fix: https://github.com/suspensive/react/issues/302

test(react): add useIsomorphicLayoutEffect Test Code

---

configs/eslint-config-js/package.json
configs/eslint-config-ts/noimport.js
configs/eslint-config-ts/package.json
configs/eslint-config/package.json
docs/package.json
package.json
pnpm-lock.yaml

chore: eslint to latest

---

docs/package.json
docs/src/pages/_app.mdx
pnpm-lock.yaml
websites/visualization/package.json
websites/visualization/src/app/layout.tsx

GA initialization to replace Vercel Analytics

docs(ga): initialization

---

.vscode/extensions.json
.vscode/settings.json
configs/eslint-config-js/noimport.js
configs/eslint-config-js/package.json
pnpm-lock.yaml

I add cspell as eslint to reduce unintended wrong spell during Pull Request time

ci: add cspell plugin for eslint

---

docs/package.json
package.json
packages/react-await/package.json
packages/react-query/package.json
packages/react/package.json
pnpm-lock.yaml
websites/visualization/package.json

chore(deps): unify version of @types/node

---

docs/src/pages/_app.mdx

clarity initialization recommended by @minsoo-web 

chore(docs): clarity initialization

---

.github/dependabot.yml

ci(dependabot): init

---

.changeset/grumpy-cooks-tease.md
packages/react-await/package.json

I updated @suspensive/react-await's package.json

fix(react-await): update package.json

---

.changeset/twelve-deers-scream.md
packages/react-query/package.json

fix #361 
remove unnecessary bundledDependencies

fix(react-query): remove bundledDependencies

---

.changeset/clean-tigers-grow.md
packages/react-query/src/QueryAsyncBoundary.tsx
packages/react/src/AsyncBoundary.tsx
packages/react/src/Suspense.tsx
packages/react/src/wrap.ts

I remove unnecessary as by Object.assign

refactor(react, react-query): remove unnecessary `as` by `Object.assign`

---

.github/workflows/release.yml

I remove authors on changeset version workflow

ci(release.yml): remove authors on version

---

codecov.yml

ci(codecov): update paths correctly

---

codecov.yml
package.json
pnpm-lock.yaml

chore: update versions of vitest

---

docs/v1/src/components/HomePage.tsx
docs/v1/src/pages/_meta.en.json
docs/v1/src/pages/index.en.mdx
docs/v1/src/pages/index.ko.mdx
docs/v1/theme.config.tsx
docs/v2/src/components/HomePage.tsx
docs/v2/src/pages/_meta.en.json
docs/v2/src/pages/index.en.mdx
docs/v2/src/pages/index.ko.mdx
docs/v2/theme.config.tsx

docs: add menu for versions

---

codecov.yml

chore(codecov.yml): ignore '**/*.test-d.*'

---

.github/labeler.yml
docs/v1/src/pages/_meta.en.json
docs/v1/src/pages/_meta.ko.json
docs/v1/src/pages/docs/_meta.ko.json
docs/v1/theme.config.tsx
docs/v2/src/pages/_meta.en.json
docs/v2/src/pages/_meta.ko.json
docs/v2/src/pages/docs/_meta.en.json
docs/v2/src/pages/docs/_meta.ko.json
docs/v2/src/pages/docs/migrate-to-v2.en.mdx
docs/v2/src/pages/docs/migrate-to-v2.ko.mdx
docs/v2/theme.config.tsx

docs: migration guide init

---

docs/v1/theme.config.tsx
docs/v2/theme.config.tsx

Add discord channel link to docs using `chat` in theme.config

chore(docs): add discord icon to header using chat area

---

.changeset/weak-melons-learn.md
configs/tsup/src/index.ts
turbo.json

close #465 
You can check docs for this options in tsup
[minify option](https://tsup.egoist.dev/#minify-output)
[treeshake option](https://tsup.egoist.dev/#tree-shaking)

chore: add tsup config for reduce bundle size and tresshake

---

docs/v1/next.config.js
docs/v2/next.config.js
docs/v2/src/pages/docs/migrate-to-v2.en.mdx

wip: Docs/migrate v2

---

.changeset/shy-moles-tap.md
packages/react/src/ErrorBoundary.spec.tsx
packages/react/src/ErrorBoundary.tsx
packages/react/src/ErrorBoundaryGroup.spec.tsx
packages/react/src/ErrorBoundaryGroup.tsx
packages/react/src/utils/assert.ts

fix #507 
remove assert.message to reduce bundle size

fix(react): remove assert.message

---

packages/react/src/DevMode.spec.tsx
packages/react/src/contexts/SuspensiveDevModeContext.spec.tsx
packages/react/src/contexts/SuspensiveDevModeContext.ts

test(react): add test cases for DevMode

---

.github/workflows/ci.yml
configs/eslint-config-ts/index.js
package.json
packages/react-image/vitest.config.ts
packages/react-image/vitest.setup.ts
packages/react-query/package.json
packages/react-query/src/useSuspenseInfiniteQuery.test-d.ts
packages/react-query/src/useSuspenseQueries.test-d.ts
packages/react-query/src/useSuspenseQuery.test-d.ts
packages/react-query/tsconfig.check.json
pnpm-lock.yaml
turbo.json

fix #545 
I remove unnecessary tsd to replace it by vitest

fix(react-query): remove tsd

---

.changeset/sour-geese-do.md
packages/react-image/src/SuspenseImage.tsx
packages/react-image/src/index.ts
websites/visualization/src/app/react-image/page.tsx

fix #395
I rename Image -> SuspenseImage

refactor(react-image): rename Image -> SuspenseImage

---

.changeset/strange-jobs-mate.md
packages/react/src/AsyncBoundary.spec.tsx
packages/react/src/Delay.spec.tsx
packages/react/src/ErrorBoundary.spec.tsx
packages/react/src/ErrorBoundary.tsx
packages/react/src/ErrorBoundaryGroup.spec.tsx
packages/react/src/ErrorBoundaryGroup.tsx
packages/react/src/Suspense.spec.tsx
packages/react/src/Suspensive.spec.tsx
packages/react/src/utils/assert.spec.ts
packages/react/src/utils/assert.ts
packages/react/src/utils/hasResetKeysChanged.spec.ts
packages/react/src/wrap.spec.tsx

fix(react): assert message correctly, test code simply

---

.changeset/shy-carrots-beg.md
configs/tsup/src/index.ts

fix(tsup): remove treeshaking, minification

---

packages/react/src/ErrorBoundaryGroup.tsx

I remove ErrorBoundaryGroup.Reset

feat(react): remove ErrorBoundaryGroup.Reset

---

.changeset/happy-scissors-wait.md
examples/next-streaming-react-query/package.json
examples/next-streaming-react-query/src/app/PageClientComponent.tsx
examples/next-streaming-react-query/src/app/components/Text.tsx
examples/next-streaming-react-query/src/app/components/Text2.tsx
examples/next-streaming-react-query/src/app/providers.tsx
packages/react/src/contexts/SuspensiveDevModeContext.ts
pnpm-lock.yaml

fix #655 
@lunelson Thanks Lu Nelson we could catch this bug quickly because of your reporting issue.
I added you as co-author for this Pull Request. Thanks

fix(react): add getServerSnapshot of use-sync-external-store in for syncDevMode in SSR environment

---

docs/suspensive.org/src/pages/docs/react-image/Image.en.mdx
docs/suspensive.org/src/pages/docs/react-image/Image.ko.mdx

update docs for `@suspensive/react-image`
please check preview docs

docs: update import line for react-image

---

.github/workflows/code-coverage.yml

ci(codecov): version up to v4

---

codecov.yml

ci(codecov): flags

---

codecov.yml

ci(codecov): use flag_management field

---

.github/workflows/ci.yml
.lighthouserc.cjs
websites/visualization/tsconfig.json

ci(lighthouse): only for suspensive.org

---

.lighthouserc.cjs
package.json

ci(lighthouse): for monorepo

---

codecov.yml

chore(codecov): ignore some files

---

.changeset/real-vans-raise.md
docs/suspensive.org/src/pages/docs/react/Delay.en.mdx
docs/suspensive.org/src/pages/docs/react/DevMode.en.mdx
docs/suspensive.org/src/pages/docs/react/DevMode.ko.mdx
packages/react/src/Delay.tsx
packages/react/src/DevMode.tsx
packages/react/src/ErrorBoundary.tsx
packages/react/src/Suspense.tsx
packages/react/src/contexts/SuspensiveDevModeContext.tsx
packages/react/src/index.ts
packages/react/src/utility-types/PropsWithDevMode.ts

I made all experimental interfaces as stable for v2 in @suspensive/react, @suspensive/react-query

feat(*): remove all experimental interface

---

.changeset/khaki-singers-mix.md
packages/react-query/src/useSuspenseInfiniteQuery.ts
packages/react-query/src/useSuspenseQueries.ts
packages/react-query/src/useSuspenseQuery.ts
packages/react-query/src/utility-types/OmitKeyof.test-d.ts
packages/react-query/src/utility-types/OmitKeyof.ts
packages/react-query/src/utility-types/index.ts

Same with https://github.com/suspensive/react/pull/816

fix(react-query): add OmitKeyof to type strictly

---

packages/react-query/src/SuspenseInfiniteQuery.test-d.tsx
packages/react-query/src/SuspenseQuery.test-d.tsx
packages/react-query/src/useSuspenseInfiniteQuery.test-d.ts
packages/react-query/src/useSuspenseQueries.test-d.ts
packages/react-query/src/useSuspenseQuery.test-d.ts
packages/react-query/src/useSuspenseQuery.ts

chore(react-query): remove dist to original src for vitest type test

---

.eslintrc.cjs
.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg

chore(*): add @coauthors/prepare-commit-msg

---

.changeset/wicked-mails-check.md
packages/react-query/src/SuspenseInfiniteQuery.test-d.tsx
packages/react-query/src/SuspenseQuery.test-d.tsx
packages/react/src/ErrorBoundary.test-d.tsx
packages/react/src/ErrorBoundary.tsx
packages/react/src/ErrorBoundaryGroup.test-d.tsx
packages/react/src/ErrorBoundaryGroup.tsx

Same reason with https://github.com/suspensive/react/pull/887

fix(react): change return type of Consumers as JSX.Element

---

.changeset/honest-peas-wink.md
packages/react/src/Delay.test-d.tsx
packages/react/src/Delay.tsx

fix(react): return type of Delay should be JSX.Element

---

docs/suspensive.org/src/pages/docs/react-await/Await.en.mdx
docs/suspensive.org/src/pages/docs/react-await/Await.ko.mdx
docs/suspensive.org/src/pages/docs/react-query/SuspenseQuery.en.mdx
docs/suspensive.org/src/pages/docs/react-query/SuspenseQuery.ko.mdx
docs/suspensive.org/src/pages/docs/react-query/migrate-to-v2.en.mdx
docs/suspensive.org/src/pages/docs/react-query/migrate-to-v2.ko.mdx
docs/suspensive.org/src/pages/docs/react/migrate-to-v2.en.mdx
docs/suspensive.org/src/pages/docs/react/migrate-to-v2.ko.mdx
docs/suspensive.org/src/pages/docs/react/wrap.en.mdx
docs/suspensive.org/src/pages/docs/react/wrap.ko.mdx

docs(*): fix typos

---

.changeset/lazy-fans-sell.md
packages/react-query/src/QueryErrorBoundary.tsx

fix(react-query): update QueryErrorBoundary's jsdoc

---

.changeset/neat-poets-drive.md
configs/eslint-config/package.json
configs/eslint-config/react.js
configs/test-utils/src/index.tsx
packages/react/src/Delay.spec.tsx
packages/react/src/Delay.tsx
packages/react/src/ErrorBoundary.tsx
packages/react/src/ErrorBoundaryGroup.spec.tsx
packages/react/src/ErrorBoundaryGroup.tsx
packages/react/src/Suspensive.spec.tsx
packages/react/src/Suspensive.tsx
packages/react/src/models/SuspensiveError.ts
pnpm-lock.yaml
websites/visualization/src/app/react/useErrorBoundary/page.tsx

ci(*): add eslint-plugin-react-compiler to prepare react 19

---

.gitignore
packages/react/package.json
packages/react/vitest.config.ts
turbo.json

ci(react): update benchmark field of vitest.config.ts

---

docs/suspensive.org/src/pages/docs/react-query/SuspenseQueries.en.mdx
docs/suspensive.org/src/pages/docs/react-query/SuspenseQueries.ko.mdx
docs/suspensive.org/src/pages/docs/react-query/SuspenseQuery.en.mdx
docs/suspensive.org/src/pages/docs/react-query/SuspenseQuery.ko.mdx
docs/suspensive.org/src/pages/docs/react-query/_meta.en.json
docs/suspensive.org/src/pages/docs/react-query/_meta.ko.json

- Wrote the documentation for `<SuspenseQueries/>`.
- Fixed a typo in the import statement in the example for `<SuspenseQuery/>`.

docs(suspensive.org): update docs for `<SuspenseQueries/>`, `<SuspenseQuery/>`

---

docs/suspensive.org/src/pages/docs/react-query/installation.en.mdx
docs/suspensive.org/src/pages/docs/react-query/installation.ko.mdx
docs/suspensive.org/src/pages/docs/react-query/motivation.en.mdx
docs/suspensive.org/src/pages/docs/react-query/motivation.ko.mdx

| installation | motivation |
| --- | --- |
|<img width="863" alt="image" src="https://github.com/toss/suspensive/assets/39869096/07fbfa04-b5a5-4612-8d42-bffbf003af47">|<img width="871" alt="image" src="https://github.com/toss/suspensive/assets/39869096/2fe93fe5-b009-4e05-b3b8-ec46e73cf47f">|

docs(react-query): update react-query for universal

---

.github/actions/pnpm-setup-node/action.yml
package.json
pnpm-lock.yaml

close https://github.com/toss/suspensive/issues/985

chore(pnpm): update version

---

docs/suspensive.org/theme.config.tsx

docs(suspensive.org): add x link

---

.changeset/config.json

fix(changeset): fix version of @suspensive/react-query-* with @suspensive/react-query

---

docs/suspensive.org/src/pages/docs/react-query/useSuspenseInfiniteQuery.en.mdx
docs/suspensive.org/src/pages/docs/react-query/useSuspenseInfiniteQuery.ko.mdx
docs/suspensive.org/src/pages/docs/react-query/useSuspenseQueries.en.mdx
docs/suspensive.org/src/pages/docs/react-query/useSuspenseQueries.ko.mdx
docs/suspensive.org/src/pages/docs/react-query/useSuspenseQuery.en.mdx
docs/suspensive.org/src/pages/docs/react-query/useSuspenseQuery.ko.mdx

Add sandpack examples to useSuspenseQuery, useSuspenseQueries, and useSuspenseInfiniteQuery.

docs(suspensive.org): add sandpack examples to useSuspenseQuery, useSuspenseQueries, and useSuspenseInfiniteQuery

---

.changeset/eight-mice-smile.md
packages/react-query-4/package.json

fix(react-query-4): correct package.json's repository directory

---

.changeset/tasty-pets-play.md
packages/react-query/src/scripts/cli.spec.ts
packages/react-query/src/scripts/utils/commands.spec.ts
packages/react-query/src/scripts/utils/commands.ts

I've added you as a co-author! @juno7803 
Thank you for your valuable feedback! Thanks to you, the explanation has become even better.
I have made the API display static for now. In the next version, I will make it dynamic to list and display the APIs. https://github.com/toss/suspensive/issues/1000#issuecomment-2197635287
| version 4 | version 5|
| --- | --- |
|<img width="472" alt="image" src="https://github.com/toss/suspensive/assets/39869096/2e4e4adf-c2db-4b19-bab4-e847075aae09">|<img width="475" alt="image" src="https://github.com/toss/suspensive/assets/39869096/1a5f6afa-d2a5-498b-99f6-a10049ea3fd1">|

feat(react-query): more descriptions for cli status

---

.changeset/chatty-donkeys-hunt.md
README.md
docs/suspensive.org/src/pages/docs/react-query/_meta.en.json
docs/suspensive.org/src/pages/docs/react-query/_meta.ko.json
docs/suspensive.org/src/pages/docs/react-query/infiniteQueryOptions.en.mdx
docs/suspensive.org/src/pages/docs/react-query/infiniteQueryOptions.ko.mdx
packages/react-query-4/src/SuspenseInfiniteQuery.test-d.tsx
packages/react-query-4/src/SuspenseQueries.test-d.tsx
packages/react-query-4/src/SuspenseQuery.test-d.tsx
packages/react-query-4/src/index.ts
packages/react-query-4/src/infiniteQueryOptions.test-d.tsx
packages/react-query-4/src/infiniteQueryOptions.ts
packages/react-query-4/src/useSuspenseInfiniteQuery.test-d.ts
packages/react-query-4/src/useSuspenseQuery.test-d.ts
packages/react-query/src/scripts/utils/commands.ts

- infiniteQueryOptions (experimental)
- add tests for infiniteQueryOptions, queryOptions

feat(react-query): add infiniteQueryOptions

---

.changeset/tidy-moons-move.md
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/labeler.yml
codecov.yml
packages/promise/.eslintrc.cjs
packages/promise/LICENSE
packages/promise/README.ko.md
packages/promise/README.md
packages/promise/package.json
packages/promise/src/index.spec.ts
packages/promise/src/index.ts
packages/promise/tsconfig.json
packages/promise/tsup.config.ts
packages/promise/vitest.config.ts
packages/promise/vitest.setup.ts
pnpm-lock.yaml

related #65 
Rename @suspensive/react-await -> @suspensive/promise and we want to merge this feature in @suspensive/react
Initiate with @SEOKKAMONI

feat(promise): add new package @suspensive/promise

---

package.json
packages/react/src/ErrorBoundary.spec.tsx
pnpm-lock.yaml

chore(*): vitest v2

---

.github/workflows/ci.yml
.github/workflows/compressed-size.yml

close https://github.com/toss/suspensive/issues/967
Add the 'compressed-size-action' to check the size of the dist folder in packages.

chore: add compressed-size-action

---

.github/workflows/compressed-size.yml

https://github.com/toss/suspensive/pull/1124#issuecomment-2247381758
Update compressed-size-action pattern to include specific file extensions `(cjs, js, mjs)`

chore: update compressed-size-action pattern to include specific file extensions

---

docs/suspensive.org/src/pages/docs/contributors.en.mdx
docs/suspensive.org/src/pages/docs/contributors.ko.mdx

- add SEOKKAMONI(Seokjin Kim) as maintainer

chore(suspensive.org): add SEOKKAMONI(Seokjin Kim) as maintainer

---

.github/actions/pnpm-setup-node/action.yml
.gitignore
package.json
packages/react-query/package.json
packages/react/src/utils/defineSuspense.tsx
pnpm-lock.yaml

pnpm v9 make weird version for "workspace:^x.x.x"

chore(pnpm): version down

---

packages/cache/src/Cache.spec.tsx
packages/cache/src/CacheStore.spec.tsx

-  add a test for the reset method
- separate the methods using describe.

test(cache): Improve tests for CacheStore

---

packages/react-query/src/scripts/utils/copy.spec.ts

- add test code for copy function

test(react-query): add test code for copy function

---

packages/react/src/wrap.spec.tsx

- add test code for the Wrap class

test(react): add test code for the Wrap class

---

.changeset/calm-walls-develop.md
.changeset/config.json
knip.json
packages/cache/package.json
packages/jotai/package.json
packages/react-image/package.json
packages/react-query-4/package.json
packages/react-query-5/package.json
packages/react-query/package.json
pnpm-lock.yaml

fix(*): remove unnecessary devDeps(react-dom, @types/react-dom)

---

.changeset/itchy-spies-vanish.md
docs/suspensive.org/src/pages/docs/react-query/infiniteQueryOptions.en.mdx
docs/suspensive.org/src/pages/docs/react-query/infiniteQueryOptions.ko.mdx

- removed the WIP label.
| ko | en |
| --- | --- |
| <img width="849" alt="image" src="https://github.com/user-attachments/assets/db7fc972-e1c5-4d59-bc2e-151a1b761301">|<img width="847" alt="image" src="https://github.com/user-attachments/assets/6806860d-7bf5-4db8-803c-482bfd2a2dc8">|

docs(suspensive.org): add infiniteQueryOptions doc

---

.changeset/weak-grapes-act.md
packages/react/src/hooks/useIsChanged.spec.ts
packages/react/src/hooks/useIsChanged.ts
packages/react/src/hooks/usePrevious.spec.ts
packages/react/src/hooks/usePrevious.ts

closed: #1166 
Seperate the module as discussed in the issue above 🙏

refactor: seperate the usePrevious module

---

.changeset/shy-wolves-train.md
packages/react-query-4/src/index.ts
packages/react-query-4/src/infiniteQueryOptions.test-d.tsx
packages/react-query-4/src/queryOptions.test-d.tsx
packages/react-query-4/src/usePrefetchInfiniteQuery.ts
packages/react-query-4/src/usePrefetchQuery.ts
packages/react-query-5/src/index.ts
packages/react-query-5/src/usePrefetchInfiniteQuery.ts
packages/react-query-5/src/usePrefetchQuery.ts
packages/react-query/src/scripts/utils/package.spec.ts
packages/react-query/src/scripts/utils/package.ts

feat(react-query): add usePrefetchQuery, usePrefetchInfiniteQuery

---

.changeset/selfish-frogs-wonder.md
packages/react-query-4/src/Mutation.tsx
packages/react-query-4/src/infiniteQueryOptions.ts
packages/react-query-5/src/Mutation.tsx

feat(react-query): remove experimental jsdoc of infiniteQueryOptions,`<Mutation/>`

---

docs/suspensive.org/src/pages/docs/react-query/_meta.en.json
docs/suspensive.org/src/pages/docs/react-query/_meta.ko.json
docs/suspensive.org/src/pages/docs/react-query/usePrefetchQuery.en.mdx
docs/suspensive.org/src/pages/docs/react-query/usePrefetchQuery.ko.mdx

related with https://github.com/toss/suspensive/issues/1253
I added docs for usePrefetchQuery of @suspensive/react-query
I added @gwansikk(@suspensive/react-query active maintainer) @kangju2000(Sandpack maker) as co-author

docs(react-query): add docs for usePrefetchQuery

---

docs/suspensive.org/src/pages/docs/react-query/PrefetchQuery.en.mdx
docs/suspensive.org/src/pages/docs/react-query/PrefetchQuery.ko.mdx
docs/suspensive.org/src/pages/docs/react-query/_meta.en.json
docs/suspensive.org/src/pages/docs/react-query/_meta.ko.json

related with https://github.com/toss/suspensive/issues/1253
I added docs for PrefetchQuery
I added @gwansikk @kangju2000 as co-author

docs(react-query): add docs for PrefetchQuery

---

codecov.yml

For @suspensive/react's test coverage 100%

test(*): ignore coverage of test-utils directory

---

docs/suspensive.org/src/pages/en/docs/react-query/Mutation.mdx
docs/suspensive.org/src/pages/en/docs/react-query/_meta.tsx
docs/suspensive.org/src/pages/ko/docs/react-query/Mutation.mdx
docs/suspensive.org/src/pages/ko/docs/react-query/_meta.tsx

close: #1303 
I have written the official documentation for `<Mutation/>`

docs: add docs for `<Mutation/>`

---

packages/react-query-4/src/usePrefetchInfiniteQuery.test-d.tsx
packages/react-query-4/src/usePrefetchQuery.test-d.tsx

test(react-query-4): type test for usePrefetchQuery, usePrefetchInfiniteQuery

---

.changeset/chatty-socks-guess.md
packages/react-query-4/src/PrefetchInfiniteQuery.tsx
packages/react-query-4/src/PrefetchQuery.tsx
packages/react-query-4/src/SuspenseInfiniteQuery.tsx
packages/react-query-4/src/SuspenseQueries.tsx
packages/react-query-4/src/SuspenseQuery.tsx
packages/react-query-4/src/queryOptions.ts
packages/react-query-4/src/usePrefetchInfiniteQuery.ts
packages/react-query-4/src/usePrefetchQuery.ts
packages/react-query-4/src/useSuspenseInfiniteQuery.ts
packages/react-query-4/src/useSuspenseQueries.ts
packages/react-query-4/src/useSuspenseQuery.ts
packages/react-query-5/src/PrefetchInfiniteQuery.tsx
packages/react-query-5/src/PrefetchQuery.tsx
packages/react-query-5/src/SuspenseInfiniteQuery.tsx
packages/react-query-5/src/SuspenseQueries.tsx
packages/react-query-5/src/SuspenseQuery.tsx
packages/react/src/DefaultProps.tsx
packages/react/src/ErrorBoundary.tsx

https://github.com/toss/suspensive/pull/1365#discussion_r1849417224

docs(react-query, react): Update jsdoc link from `en/docs` to `docs`

---

configs/eslint-config/index.js

chore(eslint): add codemods to cspell words

---

docs/suspensive.org/src/components/Scrollycoding.tsx
docs/suspensive.org/src/styles/globals.css

hide the scrollbar that appears within the codehike section.
before:
https://github.com/user-attachments/assets/314edf57-35c2-4de6-8844-221ad78de9da

fix(docs): hide scrollbar in codehike

---

.changeset/angry-cameras-wonder.md
configs/eslint-config/index.js
packages/react/src/ErrorBoundary.tsx

this resolve error of @suspensive/react@3.0.0-next.1

fix(react): resolve error of @suspensive/react@3.0.0-next.1

---

docs/suspensive.org/src/app/[lang]/layout.tsx
docs/suspensive.org/src/app/_dictionaries/en.tsx
docs/suspensive.org/src/app/_dictionaries/ko.tsx
docs/suspensive.org/src/content/en/_meta.tsx
docs/suspensive.org/src/content/ko/_meta.tsx

docs(suspensive.org): banner to notice that we're preparing Suspensive v3

---

docs/suspensive.org/src/components/HomePage.tsx

fix #1446 
@yoosion030 Thanks for issuing! We fixed it

docs(suspensive.org): canvas style pointer-events none

---

.changeset/config.json
.changeset/selfish-maps-reflect.md

https://github.com/toss/suspensive/issues/1387#issuecomment-2694068402

feat(codemods): fixed version like other suspensive libraries

---

.github/workflows/broken-link-checker.yml
.github/workflows/ci.yml
.github/workflows/graph.yml
.github/workflows/knip.yml
.github/workflows/release.yml

* In CI `pnpm install` means `pnpm install --frozen-lockfile`, so i simplify it.
* https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data

ci(.github/workflows): simplify 'pnpm install' command

---

.changeset/sweet-tips-happen.md

https://github.com/toss/suspensive/pull/1485#issuecomment-2733374602
triggers a release via changeset

chore: triggers a release via changeset

---

docs/suspensive.org/src/content/en/docs/react/Delay.mdx
docs/suspensive.org/src/content/ko/docs/react/Delay.mdx

docs(react): add docs about render prop of Delay

---

configs/eslint-config/index.js

* We can use `recommended-latest` instaed of adding in `rules` in `eslint-plugin-react-hooks` `5.2.0` latest version.
* https://github.com/facebook/react/blob/main/packages/eslint-plugin-react-hooks/README.md#flat-config-eslintconfigjsts

chore(eslint-config): update 'eslint-plugin-react-hooks' config to use 'recommended-latest'

---

docs/suspensive.org/src/content/en/docs/react/ClientOnly.mdx
docs/suspensive.org/src/content/en/docs/react/Delay.mdx
docs/suspensive.org/src/content/en/docs/react/ErrorBoundary.mdx
docs/suspensive.org/src/content/en/docs/react/ErrorBoundaryGroup.mdx
docs/suspensive.org/src/content/en/docs/react/Suspense.mdx
docs/suspensive.org/src/content/ko/docs/react/ClientOnly.mdx
docs/suspensive.org/src/content/ko/docs/react/Delay.mdx
docs/suspensive.org/src/content/ko/docs/react/ErrorBoundary.mdx
docs/suspensive.org/src/content/ko/docs/react/ErrorBoundaryGroup.mdx
docs/suspensive.org/src/content/ko/docs/react/Suspense.mdx

docs(suspensive.org): docs about `with`

---

packages/react/src/Delay.spec.tsx

test(react): use fake timers strictly for Delay.spec.tsx

---

.changeset/wet-birds-repeat.md
docs/suspensive.org/src/content/en/docs/react/migration/migrate-to-v3.mdx
docs/suspensive.org/src/content/ko/docs/react/migration/migrate-to-v3.mdx
packages/react/src/Delay.tsx

detach jsdoc experimental tag for Delay's children render prop

feat(react): Delay children render prop

---

docs/suspensive.org/src/content/en/docs/changelogs.mdx
docs/suspensive.org/src/content/ko/docs/changelogs.mdx

docs(suspensive.org): add changelogs link for react-dom, codemods

---

packages/react/package.json
packages/react/src/hooks/useIsClient.spec.tsx
pnpm-lock.yaml

test(react): useIsClient test on server

---

packages/react/src/ErrorBoundary.spec.tsx

test(react): coverage for CustomError case

---

docs/suspensive.org/src/content/en/index.mdx
docs/suspensive.org/src/content/ko/index.mdx

docs(suspensive.org): add driven by the community

---

.github/workflows/ci.yml

ci: update concurrency

---

commitlint.config.cjs
commitlint.config.mjs

chore(commitlint): rename config file from '.cjs' to '.mjs'

---

docs/suspensive.org/src/content/en/docs/react-query/migration/migrate-to-v3.mdx
docs/suspensive.org/src/content/ko/docs/react-query/migration/migrate-to-v3.mdx

docs(suspensive.org): add QueryErrorBoundary is removed

---

docs/suspensive.org/src/components/HomePage.tsx
docs/suspensive.org/src/content/en/docs/contributors.mdx
docs/suspensive.org/src/content/en/docs/react-query/SuspenseInfiniteQuery.mdx
docs/suspensive.org/src/content/ko/docs/contributors.mdx
docs/suspensive.org/src/content/ko/docs/react-query/SuspenseInfiniteQuery.mdx

This PR fixes several documentation and component issues:
1. Removed empty code block in `SuspenseInfiniteQuery.mdx` that was duplicating the `PostListItem.tsx` implementation
2. Fixed CSS property name from `justifyContents` to `justifyContent` in `contributors.mdx`
3. Removed unused `version` prop from `HomePage` component type definitions that wasn't being used in the implementation

docs: fix code blocks and component props issues

---

packages/react/src/ErrorBoundary.spec.tsx
packages/react/src/ErrorBoundaryGroup.spec.tsx

test(react): add "type='button'" in button element

---

configs/eslint-config/package.json
configs/tsup/package.json
docs/suspensive.org/package.json
examples/next-streaming-react-query/package.json
examples/react-native-playground/package.json
examples/visualization/package.json
packages/codemods/package.json
packages/jotai/package.json
packages/react-dom/package.json
packages/react-native/package.json
packages/react-query-4/package.json
packages/react-query-5/package.json
packages/react-query/package.json
packages/react/package.json

chore(package.json): simplify the clean script by removing ‘&&’

---

packages/react-dom/src/FadeIn.spec.tsx

* relate https://github.com/toss/suspensive/issues/1464

test(react-dom/FadeIn): add test for default styles without 'duration' and 'timingFunction'

---

packages/react-dom/src/useFadeIn.spec.tsx

test(react-dom): add 'useFadeIn'

---

packages/react-dom/src/utils/observe.spec.ts

test(react-dom/observe): add test to ensure root ID is reused

---

packages/react-dom/src/utils/observe.spec.ts

test(react-dom/observe): add 'describe'

---

.changeset/fair-dolls-tan.md
packages/react/src/Delay.tsx

refactor(react): remove experimental comment from DelayProps type

---

packages/jotai/src/Atom.spec.tsx

* relate https://github.com/toss/suspensive/issues/1464

test(jotai): add tests for 'Atom'

---

packages/jotai/src/AtomValue.spec.tsx

* relate https://github.com/toss/suspensive/issues/1464

test(jotai): add tests for 'AtomValue'

---

packages/jotai/src/Atom.spec.tsx

test(jotai/Atom): add test for writable derived atom

---

packages/jotai/src/Atom.spec.tsx

test(jotai/Atom): add test for reading and updating async atom with Suspense

---

packages/jotai/src/Atom.spec.tsx

test(jotai): use 'screen.getByText' instead of destructuring 'getByText'

---

packages/jotai/src/Atom.spec.tsx
packages/jotai/src/SetAtom.spec.tsx

test(jotai/{Atom,SetAtom}): add case for updater function in writable atom

---

docs/suspensive.org/src/content/en/docs/jotai/installation.mdx
docs/suspensive.org/src/content/en/docs/react-dom/installation.mdx
docs/suspensive.org/src/content/en/docs/react-query/installation.mdx
docs/suspensive.org/src/content/en/docs/react-query/motivation.mdx
docs/suspensive.org/src/content/en/docs/react/installation.mdx
docs/suspensive.org/src/content/ko/docs/jotai/installation.mdx
docs/suspensive.org/src/content/ko/docs/react-dom/installation.mdx
docs/suspensive.org/src/content/ko/docs/react-query/installation.mdx
docs/suspensive.org/src/content/ko/docs/react-query/motivation.mdx
docs/suspensive.org/src/content/ko/docs/react/installation.mdx

docs(suspensive.org/content): use nextra's 'Table' component instead of native 'table'

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature_request.yml

style(.github/ISSUE_TEMPLATE): format with prettier

---

examples/next-streaming-react-query/src/app/page.tsx
examples/visualization/src/app/react/useErrorBoundary/page.tsx
examples/visualization/src/app/react/useSyncExternalStore/page.tsx
examples/visualization/src/app/react/wrap/page.tsx
examples/vite-react-18-suspense-prerender-siblings-problem/src/App.tsx

refactor(examples): add 'type="button"' to button elements

---

packages/react/src/hooks/useTimeout.spec.tsx

test(react/useTimeout): reduce overall test time with 'useFakeTimers' and 'useRealTimers'

---

packages/react-native/jest.config.ts

chore(react-native/jest.config): remove unused eslint-disable-next-line

---

packages/react/src/Delay.spec.tsx

test(react/Delay): add 'act' to remove state update warning

---

packages/react/src/DefaultProps.spec.tsx

test(react/DefaultProps): reduce overall test time with 'useFakeTimers' and 'useRealTimers'

---

knip.json

chore(knip.json): remove 'ms' from 'ignoreDependencies'

---

packages/react-dom/src/InView.spec.tsx

test(react-dom/InView): complete tests by adding missing 'expect'

---

packages/react-query/src/bin/cli.spec.ts

To resolve this ci error. but I wanna double-check if this change is right https://github.com/toss/suspensive/actions/runs/15842475445/job/44657552753

test(cli): update compatibility message in fix command test

---

packages/react-dom/src/useInView.spec.tsx

test(react-dom/useInView): complete tests by adding missing 'expect'

---

packages/react-native/jest.config.ts
packages/react-native/package.json

chore(react-native/jest.config): enable coverage collection by default

---

docs/suspensive.org/src/components/HomePage.tsx
docs/suspensive.org/src/components/Logo.tsx

Resize logo simply
**As-Is**
https://github.com/user-attachments/assets/2d23abef-a892-4b2a-b116-b406a4db17bb
**To-Be**
https://github.com/user-attachments/assets/2a562967-043e-4bb1-8636-a0b23f18e0c5

docs(suspensive.org): Modify size of logo

---

.github/actions/pnpm-setup-node/action.yml
.github/workflows/graph.yml

ci(.github): update 'actions/setup-node' to v5, 'actions/configure-pages' to v5, 'actions/upload-pages-artifact' to v4

---

.changeset/slow-wolves-sparkle.md
docs/suspensive.org/src/content/en/docs/react-query/mutationOptions.mdx
docs/suspensive.org/src/content/ko/docs/react-query/mutationOptions.mdx
packages/react-query-4/src/mutationOptions.tsx
packages/react-query-5/src/PrefetchQuery.tsx
packages/react-query-5/src/SuspenseInfiniteQuery.tsx
packages/react-query-5/src/mutationOptions.test-d.tsx
packages/react-query-5/src/mutationOptions.tsx
packages/react-query/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

mark @suspensive/react-query-5's mutationOptions as deprecated, @suspensive/react-query-4's mutationOptions as stable

feat(react-query): mark `@suspensive/react-query-5`'s `mutationOptions` as deprecated, `@suspensive/react-query-4`'s `mutationOptions` as stable

---

docs/suspensive.org/src/content/en/index.mdx
docs/suspensive.org/src/content/ko/index.mdx

- Removed an unnecessary key prop usage in the example React component.

fix(docs): delete react component key in docs
