toss/suspensive

- packages/react/src/ErrorBoundary.tsx
I changed the factor of fallback's reset function as void 
fix #2
> fix(react): remove unnecessary type in fallback

- websites/docs/intro/installation.en.md
- websites/docs/intro/installation.ko.md
There is a pnpm installation guide on other pages such as https://docs.suspensive.org/docs/react/README.i18n and https://docs.suspensive.org/docs/react-query/README.i18n, so I also add a guide related to pnpm on the intro page to match the unity.
> docs: add pnpm install guide to intro page

- .changeset/beige-ways-type.md
- .github/changeset-version.js
- .github/workflows/ci-workflow.yml
- .github/workflows/labeler-workflow.yml
- .github/workflows/release-workflow.yml
fix #16 
1. Using changeset bot in Pull Request
We can use changeset bot in Pull Request of every contributors to add `changeset log` that will make CHANGELOG.md
2. When there is a new commit on the main branch, If there is `changeset log`(inside of .changeset/*), It will make new Pull Request to bump versions of all packages. like https://github.com/manudeli/monorepo-libraries-changeset-test/pull/3 containing auto updated CHANGELOG.md files of packages
3. Then, If we merge 2.'s Pull Request, Publishing to NPM workflow will starting. like https://github.com/manudeli/monorepo-libraries-changeset-test/actions/runs/4710530002
> chore(.changeset, .github/workflows): add auto generating CHANGELOG.md

- .github/workflows/ci-workflow.yml
- .github/workflows/release-workflow.yml
I left comment to explain details.
> chore(.github/workflow): add cache, remove unnecessary type:check, node-version

- .changeset/brown-actors-sniff.md
- packages/react-query/LICENSE
fix #37 
With this PR(https://github.com/TanStack/query/pull/5259), Documentation of @suspensive/react-query was added to the Community Resources section of TanStack/query's official documentation, and then reverted by @BasixKOR's this PR(https://github.com/TanStack/query/pull/5303)
The reason we discussed was that @suspensive/react-query started from the code of @toss/react-query, but we didn't mark it in LICENSE.md.
https://gist.github.com/fbaierl/1d740a7925a6e0e608824eb27a429370
> chore(react-query): fix LICENSE.md in @suspensive/react-query to conform MIT license of toss/slash

- websites/docs/docusaurus.config.js
I add color scheme config to docusaurus.config.js [7d1753](https://github.com/suspensive/react/commit/7de17533002536586b9f2ca3719ef5e03812567f)
Using user system preferences, instead of the hardcoded ([referece](https://docusaurus.io/docs/api/themes/configuration#respectPrefersColorScheme))
https://github.com/suspensive/react/assets/57122180/c888bf86-d86e-411f-abab-f79213a5e777
> chore(doc): add color scheme config to docs config

- .changeset/thick-walls-talk.md
- codecov.yml
- configs/tsconfig/react-library.json
- packages/react/src/ErrorBoundary.spec.tsx
- packages/react/src/ErrorBoundary.tsx
- packages/react/src/ErrorBoundaryGroup.spec.tsx
- packages/react/src/ErrorBoundaryGroup.tsx
- packages/react/src/test-utils/index.tsx
- packages/react/src/utils/index.ts
When we use useErrorBoundaryGroup, we could use it even though there is no ErrorBoundaryGroup as parent component. However, in the future it will throw an error in this case.
When this Pull Request is merged, I hope to avoid forgetting to use ErrorBoundaryGroup during development.
- ErrorBoundaryGroup.spec.tsx
- ErrorBoundary.spec.tsx
> fix(react): fix useErrorBoundaryGroup to guarantee parent ErrorBoundaryGroup

- websites/docs/intro/installation.en.md
- websites/docs/intro/installation.ko.md
To ensure consistency across different sections of the documentation, the order of npm, yarn, and pnpm has been changed.
References:
- [React Section](https://suspensive.org/docs/react/README.i18n)
- [React Query Section](https://suspensive.org/docs/react-query/README.i18n)
> docs: reorder dependency managers for consistency

- pnpm-lock.yaml
- websites/docs/docusaurus.config.js
- websites/docs/i18n/ko/code.json
- websites/docs/i18n/ko/docusaurus-theme-classic/navbar.json
- websites/docs/package.json
- websites/docs/src/components/HomepageFeatures/index.tsx
- websites/docs/src/css/custom.css
- websites/docs/src/pages/index.tsx
- websites/visualization/app/react-query/playground/page.tsx
fix #87
I added search feature as [guide provided by Docusaurus](https://docusaurus.io/docs/search)
> DocSearch crawls your website once a week (the schedule is configurable from the web interface) and aggregates all the content in an Algolia index. This content is then queried directly from your front-end using the Algolia API
1. I applied this DocSearch Program
https://docsearch.algolia.com/apply
2. I added this Pull Request as guide in email from algolia
I'm so so glad to be able to provide a search feature to anyone who reads the Suspensive official documentation. 🎉
I Invited @ChanhyukPark-Tech to share our dashboard of algolia
> feat(docs): add search feature powered by docSearch

- .changeset/tiny-swans-work.md
- packages/react-query/package.json
- packages/react/package.json
This change make our packages not to have unnecessary files(ex. __test__, _category_.json, jest.config.js, jest.setup.js, tsup.config.ts, etc.) on pack time (when we use `pnpm pack` command)
> fix(react, react-query): remove unnecessary files by package.json's files

- .changeset/green-bobcats-flash.md
- configs/tsup/package.json
- package.json
- packages/react-query/package.json
- packages/react/package.json
- pnpm-lock.yaml
- websites/visualization/package.json
close #33 
- I updated version of TypeScript
- I remained TypeScript only in root. and I removed it in all packages
> fix(typescript): update version from v4 to v5

- .changeset/long-donkeys-applaud.md
- packages/react-query/tsconfig.json
- packages/react/src/AsyncBoundary.spec.tsx
- packages/react/src/Delay.spec.tsx
- packages/react/src/ErrorBoundary.spec.tsx
- packages/react/src/ErrorBoundaryGroup.spec.tsx
- packages/react/src/ErrorBoundaryGroup.tsx
- packages/react/src/Suspense.spec.tsx
- packages/react/src/SuspensiveProvider.spec.tsx
- packages/react/src/experimental/Await.spec.tsx
- packages/react/src/utils/assert.spec.ts
- packages/react/tsconfig.json
I applied assert in use case
I removed "vitest/globals" in tsconfig to prevent contributors use `assert of chai used by vitest's global.d.ts` instead of our `assert in src/utils` So I want to force contributor write where assert import from.
No error when using `assert of chai used by vitest's global.d.ts` in ErrorBoundaryGroup.tsx, not *.spec.tsx
> refactor(react): apply assert

- packages/react/src/ErrorBoundaryGroup.spec.tsx
related with #62
- Add new test scenarios to cover displayName determination in `withErrorBoundaryGroup`
- Address uncovered lines related to displayName handling
- Ensure comprehensive test coverage
AS-IS
TO-BE
> test(react): add additional displayName test cases for withErrorBoundaryGroup

- packages/react/src/ErrorBoundary.spec.tsx
related with #62
Introducing tests for the `withErrorBoundary` ensures that is working as expected and provides the necessary error boundaries for the components it wraps. The `withErrorBoundary` is designed to catch rendering errors in its child component and display a **fallback UI** instead of crashing the entire app.
AS-IS
TO-BE
> test(react): add tests for withErrorBoundary

- .changeset/ninety-yaks-flash.md
- packages/react/src/ErrorBoundary.en.mdx
- packages/react/src/ErrorBoundary.ko.mdx
- packages/react/src/experimental/Await.en.mdx
- packages/react/src/experimental/Await.ko.mdx
I updated experimental feature mark as [admonitions](https://docusaurus.io/docs/markdown-features/admonitions) of docusaurus
> docs: update experimental feature mark as admonitions of docusaurus

- .changeset/large-schools-destroy.md
- packages/react/src/ErrorBoundary.tsx
https://github.com/suspensive/react/pull/203#issuecomment-1745714118
> fix: remove awaitClient from ErrorBoundary

- packages/react/src/ErrorBoundary.en.mdx
- packages/react/src/ErrorBoundary.ko.mdx
This PR is for clear example case for #216
> advise(react/errorboundary): add & change example case

- .changeset/orange-hotels-repair.md
- packages/react/package.json
- pnpm-lock.yaml
I remove unnecessary @types/use-sync-external-store
> fix(react): remove unnecessary @types/use-sync-external-store

- CONTRIBUTING.md
- package.json
fix #243 
If we force [corepack, we don't need to notice what version we need to use for pnpm](https://pnpm.io/installation#using-corepack).
So I use preinstall of package.json and update CONTRIBUTING.md
> chore(pnpm): force corepack by preinstall

- .changeset/smooth-poets-glow.md
- packages/react-await/package.json
- packages/react-query/package.json
- packages/react/package.json
fix #271 
I added module field of package.json to define esm's entry
> fix: add module field of package.json

- configs/test-utils/src/index.ts
- package.json
- packages/react-await/src/Await.spec.tsx
- packages/react/src/AsyncBoundary.spec.tsx
- packages/react/src/Delay.spec.tsx
- packages/react/src/ErrorBoundary.spec.tsx
- packages/react/src/ErrorBoundaryGroup.spec.tsx
- packages/react/src/Suspense.spec.tsx
- packages/react/src/SuspensiveProvider.spec.tsx
- packages/react/src/hooks/useTimeout.spec.tsx
- pnpm-lock.yaml
fix #267 
@minsoo-web suggest us to add `ms` in https://github.com/suspensive/react/pull/264#discussion_r1373407757
I added `ms` as dev dependency to test apis related with time
> chore(ms): add dev dependency

- .changeset/healthy-zoos-matter.md
- configs/test-utils/src/ThrowError.tsx
- packages/react/src/hooks/useIsomorphicLayoutEffect.ts
fix #281 
I remove isClient in `useIsomorphicLayoutEffect`
> fix(react): remove useless variable assigning in useIsomorphicLayoutEffect

- configs/eslint-config-js/no-import.js
- configs/eslint-config-ts/no-import.js
- packages/react-await/src/types/Tuple.ts
- packages/react-query/src/useSuspenseQueries.ts
- packages/react/src/hooks/usePrevious.ts
fix #384 
I added eslint rule to lint TypeScript generic conventionally
Thanks to @juliusmarminge https://twitter.com/jullerino/status/1726532233824284741
> ci(eslint): add @typescript-eslint/naming-convention to lint generic

- .changeset/smooth-birds-sip.md
- configs/tsup/src/index.ts
add splitting to reduce bundle size dramatically for esm
> fix(tsup): add splitting to reduce bundle size dramatically

- .changeset/swift-moons-help.md
- configs/test-utils/package.json
- packages/react-await/package.json
- packages/react-await/src/Await.tsx
- packages/react-image/package.json
- packages/react-image/src/Load.tsx
- packages/react-query/package.json
- packages/react/package.json
- pnpm-lock.yaml
fix #183 
I remove target react v16, v17, unnecessary use-sync-external-store
> feat(*): remove target react v16, v17, unnecessary use-sync-external-store

- .changeset/rich-flies-turn.md
- packages/react-query/src/SuspenseInfiniteQuery.test-d.tsx
- packages/react-query/src/SuspenseInfiniteQuery.tsx
- packages/react-query/src/SuspenseQuery.test-d.tsx
- packages/react-query/src/SuspenseQuery.tsx
- packages/react-query/src/index.ts
- packages/react-query/src/useSuspenseInfiniteQuery.test-d.ts
- packages/react-query/src/useSuspenseInfiniteQuery.ts
- packages/react-query/src/useSuspenseQuery.test-d.ts
- packages/react-query/src/useSuspenseQuery.ts
> feat(react-query): add `<SuspenseQuery/>`, `<SuspenseInfiniteQuery/>`

- .changeset/cyan-baboons-clean.md
- packages/react/src/AsyncBoundary.tsx
- packages/react/src/Suspense.tsx
- packages/react/src/contexts/DefaultOptionsContexts.ts
- packages/react/src/utility-types/OmitKeyOf.ts
- packages/react/src/utility-types/OmitKeyof.test-d.ts
- packages/react/src/utility-types/OmitKeyof.ts
- packages/react/src/utility-types/index.ts
- packages/react/src/wrap.tsx
related with https://github.com/TanStack/query/pull/7139
This change update `OmitKeyof` to validate Omitting keys should be keyof Omitted Object Type
As shown below, the inconvenience of having to manually remove unnecessary fields can be identified early on at the type level with `OmitKeyof`.
- https://github.com/TanStack/query/pull/6907/files
- https://github.com/TanStack/query/pull/7139#discussion_r1530890783
I made test-d to type-test `OmitKeyof`
- For complex types using `Omit`, I want to reduce the difficulty of library maintenance for it.
- `OmitKeyof` provide autocomplete by extending keyof TObject
- `OmitKeyof` check strictly second type parameter of it by extending keyof TObject
- `OmitKeyof` prevent library contributors make misspell like queryTey or qeuryKey
- Library users …
> fix(react): add OmitKeyof safely and test cases for it

- packages/react-await/src/utils/hasResetKeysChanged.spec.ts
- packages/react-await/src/utils/isPlainObject.spec.ts
- packages/react/src/utils/hasResetKeysChanged.spec.ts
This pull request aims to improve test clarity by **separating success and failure descriptions** into distinct `describe` blocks. I believe this change will enhance readability and maintainability by clearly distinguishing between different test scenarios.
I would appreciate your feedback on this approach. Thank you! :)
Key changes:
- Separate `describe` blocks for success and failure cases.
- Updated test descriptions for clarity.
> test(react, react-await): separate success & failure descriptions

- .changeset/strange-hats-walk.md
- packages/react-query/src/SuspenseInfiniteQuery.test-d.tsx
- packages/react-query/src/SuspenseInfiniteQuery.tsx
- packages/react-query/src/SuspenseQuery.test-d.tsx
- packages/react-query/src/SuspenseQuery.tsx
SuspenseQuery, SuspenseInfiniteQuery's return type should be JSX.Element not just ReactNode
> fix(react-query): fix SuspenseQuery, SuspenseInfiniteQuery's return type

- .changeset/tender-bees-wait.md
- packages/react-query/src/index.ts
- packages/react-query/src/utils/index.ts
- packages/react-query/src/utils/isVersion.spec.ts
- packages/react-query/src/utils/isVersion.ts
We expect version of @tanstack/react-query's as only v4. so we warn it with this change to promote installing correct version
> fix(react-query): easier to know constraint @tanstack/react-query v4 runtimely

- .changeset/gold-roses-nail.md
- packages/react-query/src/useSuspenseQueries.ts
fixed: #889
Fixes a bug where the TypeScript engine would hang due to the complex return type of useSuspenseQueries.
```ts
// build -> dist/useSuspenseQueries.d.ts
/**
* SuspenseQueriesResults reducer recursively maps type param to results
*/
type SuspenseQueriesResults<T extends Array<any>, TResult extends Array<any> = [], TDepth extends ReadonlyArray<number> = []> = TDepth['length'] extends MAXIMUM_DEPTH ? Array<UseSuspenseQueryResult> : T extends [] ? [] : T extends [infer Head] ? [...TResult, GetSuspenseResults<Head>] : T extends [infer Head, ...infer Tail] ? SuspenseQueriesResults<[...Tail], [...TResult, GetSuspenseResults<Head>], [...TDepth, 1]> : T extends Array<UseSuspenseQueryOptions<infer TQueryFnData, infer TError, infer TData, any>> ? Array<UseSuspenseQueryResult<unknown …
```
> fix(react-query): improved TypeScript engine halt due to return type inference in useSuspenseQueries

- .changeset/serious-dolls-heal.md
- packages/react-query/src/useSuspenseInfiniteQuery.ts
- packages/react-query/src/useSuspenseQueries.ts
Updates the JSDoc for the `useSuspenseQueries` and `useSuspenseInfiniteQuery` functions.
> chore(react-query): update JSDoc for `useSuspenseQueries`, `useSuspenseInfiniteQuery`

- README.md
|<img width="812" alt="image" src="https://github.com/toss/suspensive/assets/39869096/fb39e36b-7c47-4da3-8351-8479f8df669e">|<img width="1072" alt="image" src="https://github.com/toss/suspensive/assets/39869096/b36f21ba-2115-4ba0-aca2-623500d7e3d9">|
|---|---|
| Broken link | Clicked `@tanstack/react-query with suspense` link |
> docs: fix broken link in `README.md`

- .changeset/fair-mayflies-knock.md
- packages/react-query/bin/suspensive-react-query-switch.js
- packages/react-query/package.json
- packages/react-query/scripts/postinstall.js
- packages/react-query/scripts/switch.js
- packages/react-query/scripts/utils.js
- packages/react-query/src/v4/index.ts
- packages/react-query/src/v5/index.ts
- packages/react-query/tsup.config.ts
`@suspensive/react-query` now automatically identifies the installed version of `@tanstack/react-query` and uses either `@suspensive/react-query-4` or `@suspensive/react-query-5` accordingly.
> This is the list of remaining tasks. It may be added to or revised.
The mechanism for identifying the version of `@tanstack/react-query` and selecting the appropriate `@suspensive/react-query-x` to use is similar to `vue-demi`.
- https://github.com/vueuse/vue-demi
When `@suspsensive/react-query` is added as a dependency, the `postinstall` script fetches the version of `@tanstack/react-query` and overlays the build files of `@suspensive/react-query-x` at the entry point (build root) to ensure the appropriate version is used.
```json
// package.json
// ...
"exports": {
".": {
"import": {
"types": …
```
> feat(react-query): universal react-query for suspensive 4 and 5

- pnpm-lock.yaml
In this [PR](https://github.com/toss/suspensive/pull/963), the TypeScript version in the lockfile was changed to my local version "5.5.2", so I reverted it. 😅
> chore: revert pnpm lockfile

- .changeset/breezy-colts-lick.md
- configs/tsup/src/index.ts
- packages/react-query/tsup.config.ts
- Since the current project uses `configs/tsup`, I have added the configuration for scripts.
- Currently, this script is only used in the react-query package, but there is potential to use this config in other packages in the future.
> feat(configs): add options for scripts

- package.json
close https://github.com/toss/suspensive/issues/990
> chore(package.json): add concurrency option for dev script

- docs/suspensive.org/src/pages/_meta.en.json
- docs/suspensive.org/src/pages/_meta.ko.json
In the development environment, error is occurring
When setting [`type: 'menu'` in Nextra](https://nextra.site/docs/docs-theme/page-configuration#menus), it is collapsed by default and it does not provide the themes property. so we remove it.
> chore(suspensive.org): remove unnecessary theme property from _meta.json files

- docs/suspensive.org/src/components/Sandpack/baseTemplate.ts
- docs/suspensive.org/src/pages/docs/react/ErrorBoundaryGroup.en.mdx
- docs/suspensive.org/src/pages/docs/react/ErrorBoundaryGroup.ko.mdx
Add ErrorBoundaryGroup examples using sandpack.
> docs(suspensive.org): add ErrorBoundaryGroup examples using sandpack

- packages/react-await/src/Await.spec.tsx
This PR improves the test coverage for `react-await`. In detail, it adds the test case for `unsubscribe` method in the `AwaitClient` class.  
- [✅] I did below actions if need
> test(react-await): improve test coverage for `await.spec.tsx` (`unsubscribe` method)

- docs/suspensive.org/src/pages/docs/react-query/queryOptions.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/queryOptions.ko.mdx
Add sandpack examples to queryOptions.
> docs(suspensive.org): add sandpack examples to queryOptions

- docs/suspensive.org/src/pages/docs/react-query/SuspenseInfiniteQuery.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/SuspenseInfiniteQuery.ko.mdx
- docs/suspensive.org/src/pages/docs/react-query/SuspenseQueries.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/SuspenseQueries.ko.mdx
- docs/suspensive.org/src/pages/docs/react-query/SuspenseQuery.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/SuspenseQuery.ko.mdx
- docs/suspensive.org/src/pages/docs/react-query/useSuspenseInfiniteQuery.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/useSuspenseInfiniteQuery.ko.mdx
Add sandpack examples to SuspenseQuery, SuspenseQueries, and SuspenseInfiniteQuery.
I found a type error that occurs when passing the return value of queryOptions as a property to SuspenseInfiniteQuery. Since Sandpack doesn't catch type errors, I'm submitting this PR while creating a separate issue for the type problem. (Issue: https://github.com/toss/suspensive/issues/1015)
> docs(suspensive.org): add sandpack examples to SuspenseQuery, SuspenseQueries, and SuspenseInfiniteQuery

- .changeset/lazy-coins-appear.md
- docs/suspensive.org/src/pages/docs/react-query/tanstack-query-compatibility.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/tanstack-query-compatibility.ko.mdx
- docs/suspensive.org/src/pages/docs/react/Delay.ko.mdx
- packages/react-query-4/src/SuspenseInfiniteQuery.tsx
- packages/react-query-4/src/SuspenseQueries.tsx
- packages/react-query-4/src/SuspenseQuery.tsx
- packages/react-query-4/src/queryOptions.ts
- packages/react-query-5/src/QueryErrorBoundary.tsx
- packages/react-query-5/src/SuspenseInfiniteQuery.tsx
- packages/react-query-5/src/SuspenseQueries.tsx
- packages/react-query-5/src/SuspenseQuery.tsx
- packages/react-query/src/scripts/utils/commands.spec.ts
- packages/react-query/src/scripts/utils/commands.ts
close #1036 
I stabilize all interfaces of @suspensive/react-query before @gwansikk trying Pull Request to add Suspensive as TanStack Query v5 Community Resources
> fix(react-query): remove experimental in jsdoc

- docs/suspensive.org/package.json
- docs/suspensive.org/src/components/BubbleChart.tsx
- docs/suspensive.org/src/components/index.ts
- docs/suspensive.org/src/lib/hooks/useFetchContributors.ts
- docs/suspensive.org/src/pages/docs/contributors.en.mdx
- docs/suspensive.org/src/pages/docs/contributors.ko.mdx
- docs/suspensive.org/src/types/index.ts
- pnpm-lock.yaml
I found the bubble chart idea for the contributors page from here https://github.com/toss/suspensive/issues/1012 really interesting, so I decided to give it a try and here's how it looks. Clicking on the bubble will redirect to each contributor's github page. 
- [✅] I did below actions if need
> feat(suspensive.org): add bubble chart for contributors page

- docs/suspensive.org/src/lib/hooks/useFetchContributors.ts
Issue: https://github.com/toss/suspensive/issues/1051
I was able to reproduce the bug only by the time this issue was posted. Afterwards, I tried clearing the cache, browsing in secret mode, and even in another macbook (which never visited the page before) and in several browsers (chrome, safari, opera, edge),  I couldn't reproduce the bug again... for now I added some defense code to where the error log pointed:
I'll keep an eye on this issue. 
- [✅] I did below actions if need
> fix(suspensive.org): add defense code for github contributors fetching

- .changeset/cold-wasps-hunt.md
- packages/react/src/Suspense.tsx
- packages/react/src/utils/defineSuspense.spec.ts
- packages/react/src/utils/defineSuspense.test-d.ts
- packages/react/src/utils/defineSuspense.tsx
close: #1058
Add the `defineSuspense` utility function discussed in the issue article above, and write the test code.
The reason we defined `SuspenseClientOnly` within `defineSuspense` is because we are getting the `"dependency cycle detected"` issue. 
If you have any additional thoughts on the above issues, please let us know!
> fix(react): add defineSuspense util function

- .changeset/little-doors-drive.md
- packages/cache/src/cacheOptions.test-d.tsx
- packages/cache/src/cacheOptions.ts
- packages/cache/src/types.ts
close #1088
- add DataTag type to cacheOptions
- add tests for cacheOptions
- ref: https://tkdodo.eu/blog/the-query-options-api
**This case is when you put only cacheKey in the parameter.**
I created a function called getCache for testing purposes and confirmed that type inference works well using cacheOptions during testing.
> feat(cache): add DataTag type to cacheOptions

- docs/suspensive.org/src/pages/docs/_meta.en.json
- docs/suspensive.org/src/pages/docs/_meta.ko.json
- docs/suspensive.org/src/pages/docs/jotai/Atom.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/Atom.ko.mdx
- docs/suspensive.org/src/pages/docs/jotai/AtomValue.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/AtomValue.ko.mdx
- docs/suspensive.org/src/pages/docs/jotai/SetAtom.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/SetAtom.ko.mdx
- docs/suspensive.org/src/pages/docs/jotai/_meta.en.json
- docs/suspensive.org/src/pages/docs/jotai/_meta.ko.json
- docs/suspensive.org/src/pages/docs/jotai/installation.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/installation.ko.mdx
- docs/suspensive.org/src/pages/docs/jotai/motivation.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/motivation.ko.mdx
> docs(suspensive.org): add docs for @suspensive/jotai

- .changeset/early-suits-watch.md
- packages/react-query/src/scripts/utils/table.ts
- I have set the Status Table to an appropriate size.
- If compatibility issues are detected, display a help message in a new row on how to fix them.
| 🟢  | ❌ |
| --- | --- |
|<img width="552" alt="image" src="https://github.com/user-attachments/assets/f6498c9a-f8c7-49bd-b745-41dc23917ae8">|<img width="553" alt="image" src="https://github.com/user-attachments/assets/582bc16a-609c-4ed1-b8ad-4448a1bbafef">|
> refactor(react-query): improve status table

- .github/workflows/ci.yml
Fix [this error](https://github.com/toss/suspensive/actions/runs/10123937476/job/27997896523?pr=1151).
I referred to this [stackoverflow](https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac/76994510#76994510).
> chore: update permissions in CI

- .github/workflows/ci.yml
Related with https://github.com/toss/suspensive/pull/1157#issuecomment-2254481894
Remove actions-next-bundle analyzer in CI.
> chore: remove actions-next-bundle analyzer in CI

- docs/suspensive.org/src/pages/docs/jotai/Atom.ko.mdx
- docs/suspensive.org/src/pages/docs/jotai/installation.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/installation.ko.mdx
- docs/suspensive.org/src/pages/docs/migrate-to-v2.ko.mdx
- docs/suspensive.org/src/pages/docs/react-image/SuspenseImage.en.mdx
- docs/suspensive.org/src/pages/docs/react-image/installation.en.mdx
- docs/suspensive.org/src/pages/docs/react-image/installation.ko.mdx
- docs/suspensive.org/src/pages/docs/react-query/installation.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/motivation.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/motivation.ko.mdx
- docs/suspensive.org/src/pages/docs/react/Delay.ko.mdx
- docs/suspensive.org/src/pages/docs/react/ErrorBoundary.en.mdx
- docs/suspensive.org/src/pages/docs/react/Suspense.ko.mdx
- docs/suspensive.org/src/pages/docs/react/installation.en.mdx
- docs/suspensive.org/src/pages/docs/react/installation.ko.mdx
I modified punctuation marks such as punctuation and space in Korean and English documents.
> docs(suspensive.org): add punctuation marks to a document

- .changeset/chilled-pets-hunt.md
- packages/cache/src/CacheStore.ts
- packages/cache/src/useCache.ts
- remove unsubscribe method
The unsubscribe method does not need to be visible to the user as a public method. Therefore, it will be hidden within the subscribe method, and the unsubscribe method will be removed.
> fix(cache): remove unsubscribe method of CacheStore

- docs/suspensive.org/src/pages/docs/react/Delay.en.mdx
- docs/suspensive.org/src/pages/docs/react/Delay.ko.mdx
Add Sandpack component to Delay.
https://github.com/user-attachments/assets/f7c87581-0d5a-4a62-ad0c-bd692873e1e0
https://github.com/user-attachments/assets/2169c92a-c699-4df9-bbb4-a34914d8b0b8
> chore: add Sandpack component to Delay

- docs/suspensive.org/src/pages/docs/react-query/motivation.en.mdx
- docs/suspensive.org/src/pages/docs/react-query/motivation.ko.mdx
- docs/suspensive.org/src/pages/docs/react-query/tanstack-query-compatibility.ko.mdx
- I deleted the callout where "@suspensive/react-query@2.2.0" was incorrectly written as "@tanstack/react-query@2.2.0".
- I have standardized the callout content for "Support both TanStack Query v4 and 5".
> docs(suspensive.org): update callout for "support both TanStack Query v4 and v5"

- .changeset/tasty-dolphins-retire.md
- packages/react-query/src/scripts/utils/commands.spec.ts
- packages/react-query/src/scripts/utils/package.spec.ts
- packages/react-query/src/scripts/utils/package.ts
- packages/react-query/src/scripts/utils/table.ts
closed: #1119 / related: #1113
- I have modified the logic for displaying the APIs that re-export tanstack/react-query v5.
| @tanstack/react-query@4 | @tanstack/react-query@5 |
| --- | --- |
|<img width="543" alt="image" src="https://github.com/user-attachments/assets/04ff703f-fe3b-4d74-9494-0ad6ffaa0da3">|<img width="548" alt="image" src="https://github.com/user-attachments/assets/b34cd121-9536-4335-94eb-f5e435001300">|
> refactor: display tanstack apis in status cli table

- .changeset/config.json
- .changeset/gentle-moles-wink.md
- docs/suspensive.org/src/pages/docs/jotai/Atom.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/Atom.ko.mdx
- docs/suspensive.org/src/pages/docs/jotai/AtomValue.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/AtomValue.ko.mdx
- docs/suspensive.org/src/pages/docs/jotai/SetAtom.en.mdx
- docs/suspensive.org/src/pages/docs/jotai/SetAtom.ko.mdx
- packages/jotai/src/Atom.test-d.tsx
- packages/jotai/src/Atom.tsx
- packages/jotai/src/AtomValue.test-d.tsx
- packages/jotai/src/AtomValue.tsx
- packages/jotai/src/SetAtom.test-d.tsx
- packages/jotai/src/SetAtom.tsx
- packages/jotai/src/utility-types/ChildrenRenderProps.ts
- packages/jotai/src/utility-types/SetAtom.ts
- packages/jotai/src/utility-types/index.ts
The changes were not significant, so I included them in a single PR. If you think the PR title is inappropriate, please feel free to change it.
- Improve type inference for atom
- Improved to ensure the same type inference as the original Jotai package.
- Add test cases
- Remove experimental tag
- in suspensive.org docs
- in jotai interface
I have tested in the local environment to ensure that it behaves the same as Jotai (across all features). Fortunately, it works well, and I believe it is production-ready, just like Jotai. 
With these improvements, I think the Jotai package is ready to be released as version `1.0.0`.
> feat(jotai): escape version 0

- .changeset/perfect-games-push.md
- packages/react-query-4/src/index.ts
- packages/react-query-4/src/infiniteQueryOptions.ts
- packages/react-query-4/src/queryOptions.ts
Add exports for queryOptions return type
Fix ts error such as `The inferred type of "X" cannot be named without a reference to "Y". This is likely not portable. A type annotation is necessary.` when emitting d.ts file
> feat(react-query-4): export UnselectedQueryOptions, SelectedQueryOptions

- docs/suspensive.org/src/components/HomePage.tsx
- docs/suspensive.org/theme.config.tsx
- Removed unnecessary `.js` extension from `useRouter` import statement to align with Next.js best practices.
- Corrected to right-0 so that the right property of className works correctly.
> fix: update useRouter import and adjust UI styling

- .changeset/tricky-chicken-provide.md
- packages/react/src/hooks/usePreservedCallback.test-d.ts
- packages/react/src/hooks/usePreservedCallback.ts
Since ₩usePreservedCallback₩ needs to accept functions of all forms, due to contravariance, it’s appropriate to set the function parameter to the lowest possible type(`never`).
However, previously it was set to `unknown`, so when you pass in a function with specified parameter types, TypeScript throws an error.
Initially, I changed it to `never`, but since `never` has a problem in situations like the one above with `implicit any`. Because `implicit any` was inferred as `never`.
Therefore, in the end, I set it to the `any` type.
> refactor(react): update `usePreservedCallback` signature

- .changeset/eleven-laws-appear.md
- packages/react/src/utils/defineSuspense.test-d.ts
- packages/react/src/utils/defineSuspense.tsx
I made modifications because, when `componentPropsClientOnly` is set to `false`, it returns `Suspense`, but the overloaded function signature indicated that it returns `SuspenseClientOnly`.
> fix(react): change `defineSuspense` function signature

- .github/actions/pnpm-setup-node/action.yml
removed the version specified in the with field of pnpm/action-setup. [when the pnpm version is already defined in the packageManager field of package.json, pnpm/action-setup can automatically recognize and use it](https://github.com/pnpm/action-setup/tree/v4/?tab=readme-ov-file#version). duplicating the version setting adds unnecessary complexity and increases maintenance overhead without added benefit.
by relying on the version specified in packageManager, this change simplifies the configuration and ensures consistency.
> chore(.github/actions/pnpm-setup-node): remove version field in with of pnpm/action-setup

- .changeset/twenty-rockets-knock.md
- .changeset/wild-days-retire.md
- packages/jotai/src/Atom.tsx
- packages/jotai/src/AtomValue.tsx
- packages/jotai/src/SetAtom.tsx
- packages/react-query-4/src/PrefetchInfiniteQuery.tsx
- packages/react-query-4/src/usePrefetchInfiniteQuery.ts
- packages/react-query-4/src/usePrefetchQuery.ts
- packages/react-query-4/src/useSuspenseInfiniteQuery.ts
- packages/react-query-4/src/useSuspenseQueries.ts
- packages/react-query-4/src/useSuspenseQuery.ts
- packages/react-query-5/src/QueryErrorBoundary.tsx
- packages/react-query-5/src/SuspenseQuery.tsx
- packages/react/src/Suspense.tsx
> fix(react-query, jotai, react): fix typo in jsdoc

- .changeset/thick-cats-marry.md
- packages/react-query-4/src/queryOptions.ts
- packages/react/src/ClientOnly.tsx
- packages/react/src/DefaultProps.tsx
- packages/react/src/Delay.tsx
- packages/react/src/ErrorBoundary.tsx
- packages/react/src/ErrorBoundaryGroup.tsx
- packages/react/src/wrap.tsx
I add JSDoc comments to `@suspensive/react` and `@suspensive/react-query-4`.
> feat(react, react-query-4): add missing JSDoc for react and react-query-4

- packages/react-query/src/bin/postinstall.spec.ts
- packages/react-query/src/bin/utils/package.spec.ts
Issue https://github.com/toss/suspensive/issues/1292
For now, I managed to add tests for `postinstall.ts` and part of `package.ts`
- [✅] I did below actions if need
> test: add tests for `react-query` package

- .changeset/few-news-push.md
- packages/react-query/src/bin/cli.ts
- packages/react-query/src/bin/postinstall.spec.ts
- packages/react-query/src/bin/postinstall.ts
- packages/react-query/src/bin/utils/commands.spec.ts
- packages/react-query/src/bin/utils/commands.ts
- packages/react-query/src/bin/utils/logger.spec.ts
- packages/react-query/src/bin/utils/logger.ts
- packages/react-query/src/bin/utils/switchVersion.spec.ts
- packages/react-query/src/bin/utils/switchVersion.ts
related: https://github.com/toss/suspensive/pull/1383#discussion_r1867193643
- add error handler in commander.js
- add logger utils (for consistency)
ref: https://github.com/tj/commander.js?tab=readme-ov-file#override-exit-and-output-handling
> feat(react-query): add cli error handling

- docs/suspensive.org/src/pages/en/docs/react-query/SuspenseInfiniteQuery.mdx
- docs/suspensive.org/src/pages/ko/docs/react-query/SuspenseInfiniteQuery.mdx
```tsx queries.ts
import { queryOptions } from '@suspensive/react-query'
import { getInfinitePosts } from './api'
export const postsInfiniteQueryOptions = () =>
queryOptions({
queryKey: ['posts'],
queryFn: ({ pageParam = 1 }) => getInfinitePosts(pageParam),
})
```
The `queries.ts` logic in the [`SuspenseInfiniteQuery`](https://suspensive.org/ko/docs/react-query/SuspenseInfiniteQuery) component example on suspensive.org was using inappropriate `queryOptions`. This PR updates the example to use `infiniteQueryOptions` instead for better accuracy and relevance.
I referred to the `getNextPageParam` section in the [useSuspenseInfiniteQuery](https://suspensive.org/ko/docs/react-query/useSuspenseInfiniteQuery) part of this document.
```tsx queries.ts
import { infiniteQueryOptions } from …
```
> docs(suspensive.org): correct queryOptions to infiniteQueryOptions in SuspenseInfiniteQuery example

- .changeset/chilly-mugs-press.md
- packages/react-query-4/package.json
- packages/react-query-5/package.json
remove below peerDeps error
We want to premote @suspensive/react-query & prevent installing @suspensive/react-query-*.  
```shell
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ @tanstack/react-query is listed by your project with version 4.0.10 (p8ab5e), which doesn't satisfy what @suspensive/react-query-5 (via @suspensive/react-query) and other dependencies request (but they have non-overlapping ranges!).
```
And I want to prevent one way to alias like below
```json
{
"dependencies": {
"@suspensive/react": "^2.18.12",
"@suspensive/react-query": "npm:@suspensive/react-query-4@^2.18.12",
}
}
```
We want to make users just use like below
```json
{
"dependencies": {
"@suspensive/react": "^3.0.0",
"@suspensive/react-query": "^3.0.0",
}
}
```
1. I read the [Contributing …
> fix(react-query): remove peerDeps error when installing @suspensive/react-query

- .changeset/empty-colts-yell.md
- .github/workflows/jsr-publish.yml
- packages/react-query/jsr.json
- scripts/jsr-utils.ts
Related with https://github.com/toss/suspensive/pull/1475
- Fixed issues in the JSR publish action.
- Replaced `npx jsr publish` with `pnpm dlx jsr publish` for better compatibility.
- Added new import paths in jsr.json to properly map package name-style imports to actual paths in JSR, ensuring correct resolution for `@suspensive/react-query`.
- Ensured the CI stops if any JSR publish attempt fails by exiting with an error code.
> fix: resolve issues in JSR publish action

- .changeset/full-moments-run.md
- .github/workflows/release.yml
Configures OIDC authentication for tokenless publishing in GitHub Actions.
> fix: configure JSR publishing with GitHub Actions OIDC

- .changeset/busy-peas-raise.md
- packages/react/jsr.json
Attempting to resolve JSR publishing issue. Testing with @suspensive/react package first.
Related issues:
- jsr-io/jsr#526
- jsr-io/jsr#632
- jsr-io/jsr#24
- jsr-io/jsr/discussions/399 
> fix: Add React import to jsr.json

- pnpm-lock.yaml
- pnpm-workspace.yaml
The CVE-2025-29927 issue does not currently affect our project, but it poses a potential risk. Therefore, I’m proposing this update as a precautionary measure to prevent any future problems.
ref: 
- https://nextjs.org/blog/cve-2025-29927
- https://github.com/vercel/next.js/security/advisories?state=published
> chore: bump next.js version for CVE-2025-29927

- .changeset/kind-waves-build.md
- packages/jotai/jsr.json
- packages/react-dom/jsr.json
- packages/react-native/jsr.json
- packages/react-query-4/jsr.json
- packages/react-query-5/jsr.json
- packages/react-query/jsr.json
- packages/react/jsr.json
- scripts/jsr-sync-versions.ts
Enhanced JSR synchronization script to optimize dependency management and applied consistent formatting to all package jsr.json files.
Additionally, we need to add CI publishing permissions for all `@suspensive` packages on JSR. Currently, only `@suspensive/react` has CI publishing enabled. As mentioned in https://github.com/toss/suspensive/pull/1485#issuecomment-2733341949, we need to link the remaining packages under the 'Publish from CI' section on https://jsr.io/@suspensive.
> chore: Improve JSR imports sync with consistent dependency formatting

- docs/suspensive.org/src/components/HomePage.tsx
- Replaced `React.ReactNode` with a direct type import: `import { type ReactNode } from 'react'`
> refactor(suspensive.org): use direct type import for ReactNode

- docs/suspensive.org/src/app/[lang]/layout.tsx
The `metadataBase` field in the docs' metadata configuration defines the base domain used to resolve relative URLs into absolute ones.
Currently, it is set to a domain that differs from the actual deployment domain (`suspensive.org`). As a result, previews using relative metadata URLs fail to load correctly.
This PR updates the `metadataBase` to `https://suspensive.org` to ensure proper resolution of relative URLs and fix the preview issue.
> fix(docs): update `metadataBase` to suspensive.org to fix relative metadata URL issues

- docs/suspensive.org/src/components/HomePage.tsx
- docs/suspensive.org/src/components/Scrollycoding.tsx
Resolves #1543
On screen sizes below `md`, there was an issue where horizontal scrolling occurred due to overly aggressive negative margins.
To fix this, the margin of `article > section` has been adjusted to `-mx-4` for smaller screens (previously -mx-12).
Additionally, in the `Scrollycoding` component, the `-mr-6` margin applied to the code block is now limited to `md` and larger breakpoints.
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td align="center">
Before
</td>
<td align="center">
After
</td>
</tr>
</table>
> fix(suspensive.org): prevent horizontal scroll on mobile by adjusting margins

- .changeset/lucky-pugs-type.md
- docs/suspensive.org/src/content/en/docs/codemods/_meta.tsx
- docs/suspensive.org/src/content/en/docs/codemods/migrateWithAPI.mdx
- docs/suspensive.org/src/content/ko/docs/codemods/_meta.tsx
- docs/suspensive.org/src/content/ko/docs/codemods/migrateWithAPI.mdx
- examples/react-native-playground/package.json
- packages/codemods/src/bin/transformRunner.ts
- packages/codemods/src/transforms/migrate-with-api.ts
- packages/codemods/src/transforms/testfixtures/migrate-with-api/migrate-with-api.input.jsx
- packages/codemods/src/transforms/testfixtures/migrate-with-api/migrate-with-api.output.jsx
- packages/codemods/src/transforms/tests/migrate-with-api.test.ts
- pnpm-lock.yaml
related: #1539 
Add a codemod that converts the `wrap` API to `with`(`ErrorBoundaryGroup`, `ErrorBoundary`, `Suspense`) for the breaking change in `@suspensive/react v3`
- Remove `wrap` from the import declaration and declare only the APIs being used.
- Convert the HoC components used in `wrap` to the `with` interface.
- This codemod has been applied and confirmed to work properly by the enterprise team I belong to.
- Out of a total of 551 components, 60 components using `wrap` were reliably converted in a 28-second operation.
import { wrap } from '@suspensive/react'
import { useSuspenseQuery } from '@suspensive/react-query'
```jsx
export const Case1 = wrap
.ErrorBoundaryGroup({ blockOutside: false })
.ErrorBoundary({
fallback: ({ error }) => <>{error.message}</>,
onError: logger.log,
}) …
```
> feat(codemods): add migrate with api codemod

- .changeset/new-drinks-sit.md
- packages/react/src/ErrorBoundary.tsx
- Updated `onReset`, `onError`, and `reset` type annotations to use arrow function types for consistency
- This change resolves the `@typescript-eslint/unbound-method` lint warning, which can occur when method signatures are passed without binding
> refactor(react): update ErrorBoundary reset type to arrow function to fix unbound-method lint error

- docs/suspensive.org/src/content/en/docs/react/Delay.mdx
This PR fixes a language inconsistency in the English documentation where the "Delay.with" section in `docs/suspensive.org/src/content/en/docs/react/Delay.mdx` was written in Korean while the rest of the document is in English.
- Translated the "Delay.with" section from Korean to English
- Maintained the same structure and content, just in the appropriate language
- Preserved the code example which remains the same
This change ensures language consistency across all English documentation. Since this file is in the `/en/docs/` path, all content should be in English to maintain proper documentation standards and improve user experience.
No changes were made to the functionality or technical content - this is purely a documentation language fix.
> docs: fix language inconsistency in Delay.with section

- .changeset/tidy-cherries-judge.md
- docs/suspensive.org/src/content/en/docs/codemods/_meta.tsx
- docs/suspensive.org/src/content/en/docs/codemods/removeNetworkmode.mdx
- docs/suspensive.org/src/content/ko/docs/codemods/_meta.tsx
- docs/suspensive.org/src/content/ko/docs/codemods/removeNetworkmode.mdx
- packages/codemods/src/bin/transformRunner.ts
- packages/codemods/src/transforms/remove-networkmode.ts
- packages/codemods/src/transforms/testfixtures/remove-networkmode/remove-networkmode.input.jsx
- packages/codemods/src/transforms/testfixtures/remove-networkmode/remove-networkmode.output.jsx
- packages/codemods/src/transforms/tests/remove-networkmode.test.ts
closed: #1539 
I have created all the necessary codemod tools for the suspensive v3 migration! Users can now safely and quickly resolve the breaking changes of v3.
- [AST Explorer](https://astexplorer.net/#/gist/e73a8fc864d3bacf96540bf601dece8a/latest)
> feat(codemods, suspensive.org): add remove networkmode codemod for v3 migration

- docs/suspensive.org/src/app/[lang]/[[...mdxPath]]/MDXContent.tsx
- docs/suspensive.org/src/app/[lang]/[[...mdxPath]]/page.tsx
This PR addresses several issues in the `docs/suspensive.org/src/app/[lang]/[[...mdxPath]]/page.tsx` file
1. Incorrect typing of `params` as a Promise, which doesn't match Next.js App Router expectations
2. Direct usage of React hooks in a server component (`useMDXComponents()`)
3. Improvements to code flow and structure
- Fixed `params` type to align with Next.js expectations (regular object instead of Promise)
- Created a dedicated `MDXContent.tsx` client component to properly handle React hooks
- Clearly separated server and client logic to improve code readability and maintainability
- Placed related files in the same directory according to Toss conventions
This change follows Next.js App Router best practices and React hooks rules. 
Server components cannot directly use React hooks, …
> fix(docs): improve Next.js page component types and structure

- packages/react/src/ErrorBoundaryGroup.spec.tsx
> test(react/ErrorBoundaryGroup): use default props in 'ErrorBoundaryGroup.with' when passed 'undefined'

- packages/react/src/ErrorBoundary.spec.tsx
> test(react/ErrorBoundary): use default props in 'ErrorBoundary.with' when passed 'undefined'

- packages/react/src/Suspense.spec.tsx
> test(react/Suspense): use default props in 'Suspense.with' when passed 'undefined'

- packages/jotai/src/Atom.spec.tsx
* relate https://github.com/toss/suspensive/pull/1610#discussion_r2131537460
> test(jotai/Atom): remove test for error when calling setAtom on read-only atom

- packages/codemods/src/transforms/utils/getTestfixtures.spec.ts
> test(codemods/getTestfixtures): add test for reading fixture files with default 'js' extension

- packages/react/src/Suspense.spec.tsx
> test(react/Suspense): reduce overall test time with 'useFakeTimers' and 'useRealTimers'

- packages/react/src/ErrorBoundary.spec.tsx
> test(react/ErrorBoundary): reduce overall test time with 'useFakeTimers' and 'useRealTimers'

- .changeset/healthy-apricots-chew.md
- docs/suspensive.org/src/components/BubbleChart.tsx
- packages/react-query-4/src/PrefetchQuery.test-d.tsx
- packages/react-query-4/src/SuspenseQueries.test-d.tsx
- packages/react-query-4/src/SuspenseQueries.tsx
- packages/react-query-4/src/SuspenseQuery.test-d.tsx
- packages/react-query-4/src/SuspenseQuery.tsx
- packages/react-query-4/src/infiniteQueryOptions.ts
- packages/react-query-4/src/queryOptions.test-d.tsx
- packages/react-query-4/src/queryOptions.ts
- packages/react-query-4/src/usePrefetchQuery.test-d.tsx
- packages/react-query-4/src/useSuspenseQueries.test-d.ts
- packages/react-query-4/src/useSuspenseQueries.ts
- packages/react-query-4/src/useSuspenseQuery.test-d.ts
- packages/react-query-4/src/useSuspenseQuery.ts
- packages/react-query/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
@ha1fstack (issue reporter), could you review these changes, please?
- Updated dependencies for @tanstack/react-query and related packages to version 4.40.0 in pnpm-lock.yaml and pnpm-workspace.yaml.
- Adjusted peer dependencies in package.json to reflect the new version.
- Deprecated certain options and types in the react-query-4 package to align with the latest API changes.
- Updated tests to accommodate changes in type expectations and removed unused imports.
Next thing to do: https://github.com/TanStack/query/pull/9334
After several years of polishing the Suspensive React Query interface — from raising the first issue to this PR and finally merging into TanStack Query v4 — it feels like we’re nearing the end of a long journey of Suspensive React Query. 감성적이게 되는 날입니다 🥲
1. I read the …
> fix(react-query): update peerDependency, @tanstack/react-query to version 4.40.0 and deprecate old options

- docs/suspensive.org/src/content/en/docs/react/lazy.mdx
- docs/suspensive.org/src/content/ko/docs/react/lazy.mdx
- packages/react/src/index.ts
- packages/react/src/lazy.spec.tsx
- packages/react/src/lazy.ts
Add `reloadOnError` option for providing a convinent way to automatically reload when loading fails.
All tests are passing
> feat(react): Add option for reloading on error

- packages/react/src/lazy.spec.tsx
- packages/react/src/lazy.ts
Fix ordering of `onError` handlers.
> fix(react): Fix ordering of onError handlers

- docs/suspensive.org/src/content/en/docs/react/migration/migrate-to-v2.mdx
- docs/suspensive.org/src/content/ko/docs/react/migration/migrate-to-v2.mdx
This PR updates the Suspensive v2 migration guide by fixing the capitalization of 'Errorboundary' to 'ErrorBoundary' and 'hoc' to 'HOC' for consistency with common conventions and to improve readability.
> docs: correct typo `Errorboundary` to `ErrorBoundary` and `hoc` to `HOC` in migration guide

- docs/suspensive.org/src/content/ko/docs/react-query/motivation.mdx
This PR changes the sentence from:
- as-is: `공식문서를 통해 당신의 팀원들이 이해하기 쉬운 공식문서를 제공하고 있고 이슈가 있을 경우 신속하게 지원합니다.`
- to-be:  `당신의 팀원들이 이해하기 쉬운 공식문서를 제공하고 있고 이슈가 있을 경우 신속하게 지원합니다.`
This reduces redundancy while preserving original meaning, improving readability and polish.
> docs: simplify sentence by removing duplicated '공식문서' wording

- docs/suspensive.org/src/content/ko/docs/react/Delay.mdx
This PR fixes a minor typo in the Delay component documentation where a duplicated comma was present in the style object for opacity within the render prop example. Removing this comma improves code correctness and example clarity.
> docs: fix duplicated comma in opacity style inside Delay render prop example

- docs/suspensive.org/src/content/en/docs/jotai/Atom.mdx
- docs/suspensive.org/src/content/ko/docs/jotai/Atom.mdx
- Removed unnecessary import of Suspense from component files where it's not used.
- Added missing imports for useAtom and ShoppingItem to reflect the usage in examples.
- Improved sentence flow by changing `Suspense를 발생할지` to `Suspense가 발생할지` for natural Korean phrasing.
These changes enhance the accuracy and readability of the Atom documentation.
> docs: update Atom docs to fix imports and improve readability

- docs/suspensive.org/src/content/en/docs/react-dom/InView.mdx
- docs/suspensive.org/src/content/ko/docs/react-dom/InView.mdx
Currently, the `key` prop is set on the div inside the `InView` render prop, which can cause React warnings or unexpected behavior. This PR moves the `key` prop to the `InView` component itself, which is the correct place for list keys.
> docs: move key prop from inner div to InView component for correct usage

- docs/suspensive.org/src/content/en/docs/react-query/migration/migrate-to-v2.mdx
- docs/suspensive.org/src/content/ko/docs/react-query/migration/migrate-to-v2.mdx
This PR addresses several issues in the React Query v2 migration guide documentation:
- Fixed typo from `@supensive/react-query` to `@suspensive/react-query`
- Corrected import statement: replaced `PostItem` with `PostListItem` for accuracy
- Removed unnecessary trailing space after `<AuthorInfo userId={userId} />`
These corrections improve the accuracy and professionalism of the documentation and examples.
> docs: correct typos and fix imports in React Query v2 migration documentation

- docs/suspensive.org/src/content/en/docs/react-query/Mutation.mdx
- docs/suspensive.org/src/content/ko/docs/react-query/Mutation.mdx
- Changed `postMutation.isLoading` to `postMutation.isPending` to match current API.
- Added missing `content` parameter in `api.editPost` call to ensure correctness.
- Corrected `api.editComment` calls to pass `content` parameter consistently instead of `comment`.
These changes improve the accuracy and consistency of the mutation example in the documentation.
> docs: fix mutation example isPending usage and unify content parameter in API calls

- docs/suspensive.org/src/content/en/docs/react-query/useSuspenseQueries.mdx
- docs/suspensive.org/src/content/ko/docs/react-query/useSuspenseQueries.mdx
This PR fixes the useQueries example in the documentation, changing from `query.data` to `query1.data` and `query2.data` to correctly reference the respective queries' data. This change improves accuracy and reduces confusion for users.
> docs: correct data access in useQueries suspense example to use query1.data, query2.data

- docs/suspensive.org/src/content/en/docs/react-query/SuspenseInfiniteQuery.mdx
- docs/suspensive.org/src/content/ko/docs/react-query/SuspenseInfiniteQuery.mdx
This PR modifies the Post type definition by adding the export keyword so that it can be imported and used in the PostListItem component example and other parts of the codebase. This improves example correctness and usage clarity.
> docs: export Post type for usage in PostListItem component example

- .github/dependabot.yml
- .github/labeler.yml
- .github/workflows/autofix.yml
- .github/workflows/broken-link-checker.yml
- .github/workflows/ci.yml
- .github/workflows/graph.yml
- .github/workflows/knip.yml
- .github/workflows/release.yml
- .prettierignore
- .vscode/settings.json
- packages/react/src/Delay.tsx
I added https://autofix.ci/ to fix PRs with prettier automatically.
We can see autofix like below [db9cb51](https://github.com/toss/suspensive/pull/1716/commits/db9cb518719381cd91fe3044450d39105afab66a)
Now contributors don't have to execute `pnpm install` to format code with prettier.
I think contributors for documentation may feel easy to do something
autofix ci will format automatically with prettier
> ci(.github/workflows): add autofix.yml

- .github/workflows/autofix.yml
- examples/react-native-playground/package.json
add packlint powered by @artechventure step to autofix workflow
We can see autofix ci's commit in [74633bc](https://github.com/toss/suspensive/pull/1722/commits/74633bcccd2ca9f94376eea4627180d6180d4517)
> ci(.github/workflows): add packlint step to autofix workflow

- .github/workflows/ci.yml
- Add `strip-hash` option to compressed-size-action in CI workflow
- Update file pattern to track all dist files instead of specific ones
- Improve bundle size tracking accuracy after tsdown migration
After migrating to tsdown (PR #1678), the bundle output filename format has changed significantly
- The 'chunk' files have disappeared and are now named like `dist/SuspenseQuery-DkWngpUn.cjs`
- Hash values in filenames change on every build, causing the `compressed-size-action` results to appear incorrectly
- Size comparisons were showing misleading results due to hash-based filename variations
- Added `strip-hash` option to group files with different hashes as the same module
- Updated the file pattern from `packages/*/dist/{index,v4,v5}.{js,cjs,mjs}` to `packages/**/dist/*.{js,cjs,mjs}` to …
> chore(ci): add strip-hash option to compressed-size-action
